### PR TITLE
Task 429 pull req appr

### LINKED ISSUE #429: Add the PR approval process steps to the contributor's guide.
## Describe the Task ##
Add the PR approval process steps to Chapter 6 of the contributor's guide.   Also work on the formatting of that chapter to get to render well on GitHub pages.
Merge into the master_v3.0 and develop branches.
Push the changes to the gh-pages branch, rendered here:
   https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None required.

### Relevant Deadlines ###
None.

### Funding Source ###
2702691

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required. John HG.
- [X] Select **scientist(s)** or **no scientist** required. Not required.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components: No impacts.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by lisagoodrich**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I've worked closely with Julie P. to update the directions in sections 6.2.2 through 6.2.2.2
I've run 'make clean html' with no errors for this section

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
Please carefully read the documentation and make sure it makes sense and looks good.  Here's the output I created:
https://ral.ucar.edu/staff/jpresto/work/METplus_lisag/Contributors_Guide/github_workflow.html

- [x] Will this PR result in changes to the test suite? **No**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] After merging, should the requestor **DELETE** the feature branch from GitHub? **Yes**</br>
Per today's METplus meeting, I will Delete the feature branch when you are done (with Julie's supervision).

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Review by georgemccabe — APPROVED** [review]
The changes look good to me. I build the docs from the branch locally and I also received no errors.

**Review by JohnHalleyGotway — COMMENTED** [review]
The PR indicates that these changes should be reviewed at:
https://ral.ucar.edu/staff/jpresto/work/METplus_lisag/Contributors_Guide/github_workflow.html
However, I don't see the "Files changed" changes reflected at that URL. Can you please double-check the web content?

**Comment by lisagoodrich** [comment]
Please try again.  You can search for this:
6.2.2. Approve a pull request using a browser

**Review by JohnHalleyGotway — APPROVED** [review]
Looks good now. Thanks!
The changes look fine to me.
I will leave it to you to merge in these changes.

**Pull request merged**
