### PR TITLE
feature 1147 final conf sorting

### LINKED ISSUE #1147: Add instructions to update old METplus configuration files that reference user-defined wrapped MET config files
Related to discussion #996

## Describe the Enhancement ##
Add useful instructions to assist users who need to update their configurations to use the wrapped MET config files in parm/met_config instead of their own MET config files. This involves determining which variables in the user's wrapped MET config file differ from the wrapped version in parm/met_config (considering the variables in the parm/met_config version that mistakenly differ from the default MET values before v4.0.0).

Respond to GitHub Discussion topic listed above with info and consider adding this information to User's Guide

### Time Estimate ###
~3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add logic for writing metplus_final.conf to move variables that are specific to that run (i.e. CLOCK_TIME) to a runtime section so that it is clear which variables are relevant if rerunning*

### Relevant Deadlines ###
4.1.0-beta3 (if possible)

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Changes in this PR
- Changed writing of final conf file at end of execution to:
  - move variables specific to runtime and user's environment to [runtime] section so remaining variables in [config] are specific to the use case
  - Remove CURRENT_* variables because they contain info about last field processed are not relevant to final conf
- Cleaned up command line argument handling for run_metplus.py to:
  - Read in each argument in order (previously explicit variable overrides were processed after all config files)
  - Get full path of config file inputs for easier debugging (in logs and final conf)
- Remove logic to allow override of METPLUS_BASE since the version of the scripts should always match the version of the run_metplus.py script that is called to avoid confusion
- Cleaned up first few lines of log output to contain more useful information and removed unnecessary text
- Other formatting cleanup and adding documentation
- Added missing table to User's Guide

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

- Ensure all tests passed

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Call run_metplus.py on a use case and review the log output
- Play with passing multiple config files and config variable overrides and verify they are read in the correct order (last occurence of a variable is used)
- Review final config file (metplus_final.conf) and verify that the list of variables in each make sense: runtime vs. config (use case specific)

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [X] Please complete this pull request review by **9/15/2021**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by j-opatz — COMMENTED** [review]
Ran a few use cases that passed with Github actions and saw no issues, including when I added multiple overrides: only the last one was chosen as the input.
However, I noticed quite a few of the use cases failed, beyond the one warned about (e.g. CyclonePlotter). Self-tested one of them, TCGen_fcstGFSO_obsBDECKS_GDF_TDF. Looks like the error is not finding the module:
ModuleNotFoundError: No module named 'metplotpy'
May need to see if the other use cases failing also refer to metplotpy modules and if it's caused by this feature branch's changes.

**Comment by georgemccabe** [comment]
> 
> 
> Ran a few use cases that passed with Github actions and saw no issues, including when I added multiple overrides: only the last one was chosen as the input.
> However, I noticed quite a few of the use cases failed, beyond the one warned about (e.g. CyclonePlotter). Self-tested one of them, TCGen_fcstGFSO_obsBDECKS_GDF_TDF. Looks like the error is not finding the module:
> ModuleNotFoundError: No module named 'metplotpy'
> May need to see if the other use cases failing also refer to metplotpy modules and if it's caused by this feature branch's changes.

@j-opatz did this happen on seneca? If so, it is due to the conda environment not having the metplotpy package installed. In GitHub Actions, the conda environment is loaded and then the package is installed from the source code right before running the tests to ensure that we are testing with the latest version of the package. I could install the package on seneca in that environment, but it would have to be updated to include the latest changes to the package periodically. If this would be useful, we could set up a way to automate it locally.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe perhaps I haven't been keeping up. Why are 5 of the GHA tests failing?
The PR text indicates that there should be no changes in results. With 4 assigned reviewers for this PR, do you have any specific direction as to which parts each of us should review?

**Comment by j-opatz** [comment]
@georgemccabe that's correct, this was on Seneca. So it looks like what caused the issue for my run is probably not what caused the Github Actions to fail.
I'd like to be able to recreate the same environment that Github Actions does and explore why some of these use cases are failing. It sounds like the package associated with this particular use case may take some effort to get stood up on Seneca. Is there another failing use case that doesn't require as much prep work on your end? I see there's a few in s2s, at least 3 of them.

**Comment by georgemccabe** [comment]
> 
> 
> @georgemccabe perhaps I haven't been keeping up. Why are 5 of the GHA tests failing?
> The PR text indicates that there should be no changes in results. With 4 assigned reviewers for this PR, do you have any specific direction as to which parts each of us should review?

@JohnHalleyGotway, most of the tests are failing due to the reoccurring cartopy issues where it cannot download the map files that it needs to run:

`/usr/local/envs/metplotpy/lib/python3.6/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/50m/physical/ne_50m_coastline.zip`

That webpage has been going down on and off for a few weeks now.

I did just notice that there is also a failure in the METdbLoad use case that may be due to a chance with another METplus component:

`pymysql.err.ProgrammingError: (1146, "Table 'mv_metplus_test.line_data_ssidx' doesn't exist")`

The changes in this PR aren't related to either error. In the initial comment of this PR, I mentioned that testing can be done by playing around with running use cases on the branch, reviewing the final config output, and ensuring that config overrides are occurring in the correct order (each file/variable argument overrides values set in previous arguments).

**Comment by jprestop** [comment]
@georgemccabe @j-opatz 
I thought that it was no longer necessary for it to download a zip file of map information after [Issue 933](https://github.com/dtcenter/METplus/issues/933), but perhaps I don't have a big picture understanding of the issue.

@georgemccabe 
Would you be able to provide some sample use cases for us to run and point us to a location where we can run this feature branch if you already have it set up somewhere?

**Comment by georgemccabe** [comment]
> 
> 
> @georgemccabe @j-opatz
> I thought that it was no longer necessary for it to download a zip file of map information after [Issue 933](https://github.com/dtcenter/METplus/issues/933), but perhaps I don't have a big picture understanding of the issue.

That issue implements a workaround to obtain the map files if a user doesn't have access to the internet to download them. I considered implementing that solution when creating the conda environments that contain cartopy but really that is a workaround that should not be needed. GHA can query the URL, but the website is offline. Updating the version of cartopy could potentially solve this issue, as a newer version may use an updated URL, but that may introduce other differences/package conflicts/issues/etc. I'm not sure what the best solution is here.

> 
> @georgemccabe
> Would you be able to provide some sample use cases for us to run and point us to a location where we can run this feature branch if you already have it set up somewhere?

Any of the use cases that were available in METplus 4.0 can be used on seneca. The INPUT_BASE value should be set to 

/d1/projects/METplus/METplus_Data

and the source code can be obtained by cloning the METplus repo and switching to the branch (feature_1147_sort_final_conf). I didn't want to suggest use cases to run because I wanted multiple use cases to be tested to ensure that the results in the final METplus conf that is generated looks good for more than 1 use case.

Note any use case that requires python embedding will need to set the MET_PYTHON_EXE to run. All of the conda environments used in automation are available on seneca in /home/met_test/.conda/envs

**Comment by georgemccabe** [comment]
The failure in the METdbLoad use case is due to a new table being added to METdatadb that may not be in the METviewer Docker image for the develop branch?

Here is the error:

`pymysql.err.ProgrammingError: (1146, "Table 'mv_metplus_test.line_data_ssidx' doesn't exist")`

Here is the change added to METdatadb:
https://github.com/dtcenter/METdatadb/commit/f9674dd50922ecc6d7c89cc8ee15ebfd7b123846

It looks like there is code to handle the line_data_ssidx table in METviewer develop:
https://github.com/dtcenter/METviewer/blob/72a8b1912eba4c2c219178ce85e25570299ee65b/sql/mv_mysql.sql#L1698

However, I recall that the METviewer Docker image had been failing (emails from DockerHub). @TatianaBurek do you know what is needed to fix the errors for the METviewer Docker image? Update: I noticed the develop image for METviewer is not failing, but perhaps the docker-compose file is using the latest stable release version which would not include the line_data_ssidx table. I think adding :develop to the METVIEWER_DOCKER_IMAGE variable in the automation scripts should fix this issue.

**Comment by georgemccabe** [comment]
https://github.com/SciTools/cartopy/issues/1849#issuecomment-916146694

Regarding the cartopy issue, it sounds like they have updated the latest conda version of cartopy to use the correct URL. The latest version appears to be v0.19.0post1 (according to https://anaconda.org/conda-forge/cartopy) but it is not clear if the change will fix the 0.17.0 and 0.18.0 versions that we use. I will try rebuilding the conda environment docker images that we use to see if that fixes it. If not, it sounds like we can obtain the downloader script from the master branch and run that to obtain the map files regardless of version.

**Comment by georgemccabe** [comment]
Confirmed changing to use develop version of METviewer docker image fixes issue with METdbLoad use case.

Rebuilding cycloneplotter env using cartopy 0.17.0 does not resolve the bad URL issue. We can either upgrade the version of cartopy to 0.19.0 and risk differences/errors due to using a new version of the package OR modify the script to create the conda environment to obtain the map download script from the master branch and run it to obtain the necessary files.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve. These changes seem fine to me. I did not actually test the intended functionality but @j-opatz did and confirmed that it works. Per @georgemccabe, switching to METviewer:develop got past the SSIDX loading issue, which is a new line type added in the MET version 10.1.0 beta2 release. The only remaining issue is with the availability of downloadable cartopy datasets but that problem/solution is unrelated to this development task.

**Review by j-opatz — APPROVED** [review]
After the discussion on this PR, I'm comfortable approving the branch changes. All of the concerns of my first comment re: failed use cases is unrelated to these changes.

**Comment by georgemccabe** [comment]
Update: I am still working through the issues with the broken use cases that use cartopy (unrelated to the changes in this PR). I was able to update the docker images that contain the conda environments that utilize cartopy to download the shape files and make them available for running the use cases. The use cases that use cycloneplotter_env and metplotpy_env are now working and I am currently rebuilding the weatherregime_env that should fix the issue for that environment.

Commit 8a642339f involves a change to the GFDLTracker_Genesis and GFDLTracker_ETC use cases (both in met_tool_wrapper) that should change the output, so the differences in those use cases are expected.

**Comment by georgemccabe** [comment]
Update: I was able to fix the broken use cases. I updated the scripts that are used to build the Docker images that contain the conda environments for running use cases that use cartopy (metplotpy and weatherregime). The URL that is used to download shapefiles changed so versions 0.17.0 and 0.18.0 will fail when they are run. I added logic to the scripts that build the environments to obtain the feature download script from the master branch of the cartopy repository and run it to download the shapefiles from the correct location. The WeatherRegime use cases download a few additional shapefile groups that were not found in the script, so I created a fork of the cartopy repository and added the missing groups to the script. I created a pull request to merge these changes into cartopy but it has not yet been approved. See SciTools/cartopy#1894 for more details. The script to recreate the environment currently uses my fork until this gets approved or I receive advice on another way to resolve the issue.

Here is a summary of the differences in the output:

* Commit 8a64233 involves a change to the GFDLTracker_Genesis and GFDLTracker_ETC use cases to use a different mean sea level pressure field (PRMSL instead of MSLET)
* @CPKalb updated the sample data for the Blocking and WeatherRegime use cases that had been messed up somehow. While investigating this @CPKalb discovered that there was a discrepancy in the data -- the WeatherRegime data should be US only and the Blocking data should be global. Previously the same GFS data was used for both sets of use cases. @CPKalb mentioned adding a check to ensure the grids are the same between the input data sets.
  * UserScript_fcstGFS_obsERA_Blocking - there is no output data for this case in the truth data, but there are output files after fixing the input data and paths in the conf files
  * UserScript_obsERA_obsOnly_Blocking - the final output plots differ but this is expected because the correct domains for the input data are now being used
  * UserScript_fcstGFS_obsERA_WeatherRegime - the s2s/fcst_weather_regime_class.txt slightly changed, but this is likely due to changes in input data described above

I am merging these changes and updating the develop-ref data set.

**Pull request merged**
