### PR TITLE
Feature 2737 release instruct

### LINKED ISSUE #2737: Documentation: Update release guide instructions for METplus Analysis components
## Describe the Task ##
While working through the release notes for the METplus-Analysis beta6 releases, I found some areas that could be improved in the documentation.

* Update the "Update Version Number for Release" for METcalcpy (note that METcalcpy needs it's version file as it is used by setup.py so add information about that file as well), METdataio (this file is also needed - without it there is a failure in the METplus use case that calls METdbLoad and it also impacts METviewer, which is using this file to determine the release version), and METplotpy to be the same as MET's section. For METviewer, there are some other details that need to be modified/considered:
   * Current: "In the METviewer/build.xml file, assign the version in the ‘dist’ target" (On line 365 of build.xml is where to modify the version - look at that line in the file and come up with a better description)
   * Current: "In the METviewer/vebapp/metviewer/metviewer1.jsp file, assign the version to <div id=’release’> and <title>" Typo with "vebapp" to correct and on line 261 and update instructions with a better description (div-id is no longer accurate, now span-id).
   * Include changes to make it more similar to MET's description.
   * George notes that the version is referenced in all of the following for METdataio: [docs/version](https://github.com/dtcenter/METdataio/blob/develop/docs/version), [docs/conf.py](https://github.com/dtcenter/METdataio/blob/367bdd2fc6a7ec5d519373928ce6d248c114fc25/docs/conf.py#L23), [pyproject.toml](https://github.com/dtcenter/METdataio/blob/367bdd2fc6a7ec5d519373928ce6d248c114fc25/pyproject.toml#L11)

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
rc1 release

### Funding Source ###
2782544 (NOAA base)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
This work was to update the METplus Analysis version number updates in Read the Docs and to make it more consistent with the other components, with specifics for the analysis tools as described in the issue.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Reviewed the modified pages in Read the Docs for formatting and typos:

METdataio:

- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metdataio_development.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metdataio_bugfix.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metdataio_official.html#update-version-number

METcalcpy:

- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metcalcpy_development.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metcalcpy_bugfix.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metcalcpy_official.html#update-version-number

METplotpy:

- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metplotpy_development.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metplotpy_bugfix.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metplotpy_official.html#update-version-number

METviewer:

- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metviewer_development.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metviewer_bugfix.html#update-version-number
- https://metplus.readthedocs.io/en/feature_2737_release_instruct/Release_Guide/metviewer_official.html#update-version-number

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review the files for typos.  These details *should* be accurate, but we can work out any problems when we cut the next release, making any necessary updates/corrections.  Please also ensure that all tests pass.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[N/A]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [x] Please complete this pull request review by **[20241111]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [x] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METplus-Wrappers-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by lisagoodrich** [comment]
@jprestop thanks for talking with me about this.  I found zero typos.  I also ran it through Google Docs too.

Per our conversation, I checked the development branch of METdataio, METplotpy, METcalcpy and METviewer for ‘docs/conf.py’, update the ‘version’, ‘release_year’, and ‘release_date’ variables for the documentation.  All of the information was there.

I approve this pull request.  (Please let me know if I left something out.  I don't review pull requests often.)

**Comment by jprestop** [comment]
> Per our conversation, I checked the development branch of METdataio, METplotpy, METcalcpy and METviewer for ‘docs/conf.py’, update the ‘version’, ‘release_year’, and ‘release_date’ variables for the documentation. All of the information was there.

This is great @lisagoodrich.  Again, many thanks for reviewing!

**Comment by jprestop** [comment]
@lisagoodrich Actually, I need one more thing. Could you please click the Approve circle on the right hand side of the attached screenshot?
Screenshot 2024-11-07 at 11 36 35 AM

**Comment by lisagoodrich** [comment]
Ignore this comment, I figured it out.

@jprestop, can you walk me through this?  Should I do this for each of the web pages above? Please send a link to the first one and I'll figure the rest out. Thanks.

**Review by lisagoodrich — APPROVED** [review]
I approve all changes.

**Comment by jprestop** [comment]
Hi Lisa.  You only have to do this once.  On this page, please navigate to the top.   You are currently on the "Conversation" tab.  Switch to the "Files Changed" tab (rightmost tab).  Click on the green "Review Changes" button on the upper right hand side.  A "Finish your review" box will pop up (shown in the image).  Please click on the circle next to "Approve" and then click "Submit Review".  I hope that helps.  I'm in a meeting now, but can meet after to walk through this if you'd like.

**Pull request merged**
