### PR TITLE
feature 1599 set climo_mean/stdev using VAR<n> variable syntax

### LINKED ISSUE #1599: Enhance climatology field settings to be consistent with fcst/obs field
Currently the climatology field can be set by using {TOOL}\_CLIMO\_[MEAN/STDEV]_FIELD i.e. GRID_STAT_CLIMO_MEAN_FIELD. However, the format of the value must match the format that is expected by the MET tool:

`GRID_STAT_CLIMO_MEAN_FIELD = {name="TMP"; level="(*,*)";}`

## Describe the Enhancement ##
It would be easier for users if the climatology field info can be set in the same way that forecast and observation fields are specified. Add support for setting {TOOL}\_CLIMO\_[MEAN/STDEV]\_VAR<n>\_[NAME/LEVELS]. The above example would be set using:

```
GRID_STAT_CLIMO_MEAN_VAR1_NAME = TMP
GRID_STAT_CLIMO_MEAN_VAR1_LEVELS = "(*,*)"
```

### Time Estimate ###
~1-2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
5.0.0

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
This PR adds support for setting climo field info using VAR<n> syntax instead of having to format the field value with the expected MET config syntax. See issue #1599 for details of what was implemented.
I added unit tests to ensure that the correct values are used in different scenarios of config settings.

I also added a function format_field_info that can replace many instances of get_field_info and is much more simple. I also rearranged and cleaned up some util logic that is part of #344 so that work does not need to be done all at once. This includes moving constant variables to metplus/util/constants.py and moving functions that handle field info into metplus/util/field_util.py.

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Added new unit tests, ensured that changes did not break existing use cases.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

* Review documentation for any copy/paste mistakes and ensure new content is clear
* Ensure all automated tests pass (no differences)
* Run existing use case that sets climo variables and ensure that using the new variables results in the expected output

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
No differences should result from these changes.

- [X] Please complete this pull request review by **6/17/22**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by j-opatz — COMMENTED** [review]
Tested out the new capability with a soon-to-be use case and found no differences in output from previous method of climate information entry (i.e. field).

I do wonder if instead of the current wording for each <TOOL>_CLIMO_ entry, we should try to mimic what's being done for the <TOOL>_[OBS/FCST]_VAR<n>_NAME and _LEVELS entries; for example,

_FCST_GRID_STAT_VAR<n>_LEVELS

    Wrapper specific field info variable. See [FCST_VAR<n>_LEVELS]_

This seems more succinct, and allows 1 place for all of the information to reside.

**Comment by georgemccabe** [comment]
@j-opatz I see what you are saying and agree it would be nice to not duplicate information. However, there is no generic form of these settings, i.e. there is no CLIMO_MEAN_FIELD_VAR\<n\>_NAME that applies to all wrappers to store that information in the glossary.

**Comment by j-opatz** [comment]
> @j-opatz I see what you are saying and agree it would be nice to not duplicate information. However, there is no generic form of these settings, i.e. there is no CLIMO_MEAN_FIELD_VAR<n>_NAME that applies to all wrappers to store that information in the glossary.

I saw that and recognize the slightly bigger challenge with creating a central source for this info. It still seems like using <TOOL_NAME>_CLIMO_MEAN_* and <TOOL_NAME>_CLIMO_STDEV_*, and listing out which tools these apply to, cuts down on the need for the longer glossary entries. The glossary entries as they are now are informative, and if it creates more work to go back and adjust it to a central but (slightly) ambiguous common entry then it can stay as it is.

**Review by j-opatz — APPROVED** [review]

**Comment by georgemccabe** [comment]
@j-opatz, I made your suggested edits to the glossary. Please review those changes for accurate/typos.

**Review by j-opatz — APPROVED** [review]
With the new changes to the layout of information (one central area vs copy-paste listing for every tool), the information seems much more compact and concise. It conveys that all the tools have access to the same climo options, which avoids the issue of "am I missing something that this tool doesn't do?". 
The only comment I have is the home for the agnostic information: currently, it resides in the glossary. To me, this reads very similar to the "Field Info" section under Section 3.6, System Configuration, Common Config Variables. Maybe it can reside there in addition to the fcst/obs information? But the content itself is great/free from any issues that I was checking for, and I approve the PR, with or without moving the information from its current location.

**Comment by georgemccabe** [comment]
@j-opatz thanks for review and feedback. I propose that we add a section after "3.6.5.10. Wrapper Specific Field Info" that mentions these variables and links to the generic glossary entries. I am going to merge this PR and we can make this change afterwards if you agree.

**Pull request merged**
