### PR TITLE
Feature 551 create pdf user guide

### LINKED ISSUE #551: Generate PDF of User's Guide
We have discussed generating a PDF of the User's Guide so users can access it offline. Also, many sponsors prefer print-out copies of documentation. I added an option to build the docs and generate a PDF copy.

To build a PDFs, you must have additional python packages (sphinx 2.4.2 or higher and rst2pdf) and set the environment variable METPLUS_DOC_PDF before running docs/build_docs.py.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)** (many)

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] Consider doing this for other projects

[MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by ksearight**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:  
       Automatically built on RTD upon push to the repo. Examined HTML and PDF outputs for formatting correctness.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:
  - Examine formatting in both HTML and PDF versions, including indentation.
  - Check quicksearch chapter differences between HTML and PDF versions.
  - Verify that the absence of graphical links in Use Cases chapter is okay in PDF version.
  - Confirm that the number of levels in TOC in PDF version is acceptable.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
       RTD correctly builds the documentation.

- [x] Do these changes include sufficient testing updates? **[Yes]**
n/a

- [x] Will this PR result in changes to the test suite? **[No]** 

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — APPROVED** [review]
I reviewed the changes that were made since I last looked over the documents and they look good. For reference, I viewed content at the following links:

* [PDF](https://metplus.readthedocs.io/_/downloads/en/feature_551_create_pdf_user_guide/pdf/)
* [HTML](https://metplus.readthedocs.io/en/feature_551_create_pdf_user_guide/)

The different versions of the quick search page look good. We will need to remember to update the sections for both version (html and latex) when we add a new quick search keyword.

The different levels of each section are a little difficult to discern since they are about the same size, but the chapter numbers help tell them apart. I don't think this is something we need to change because most users will be using the HTML version anyway.

I see the code that handles the old attempt at creating a PDF document have been removed as well.

I approve of the changes.

**Comment by georgemccabe** [comment]
@ksearight some of the use cases are failing unrelated to these documentation changes (cartopy released a new version which broke some of the automation logic to install the module). There is another pull request open that includes the fix, so you can ignore the failures in the Testing Workflow and just confirm that the Documentation Workflow does not produce a documentation_warnings.log artifact before merging.

**Comment by ksearight** [comment]
@georgemccabe CI did produce a `doc_warnings.log` file:  
```
WARNING: The config value `latex_show_pagerefs' has type `str', defaults to `bool'.
/home/runner/work/METplus/METplus/docs/Users_Guide/systemconfiguration.rst:1567: WARNING: Literal block expected; none found.
/home/runner/work/METplus/METplus/docs/Users_Guide/systemconfiguration.rst:1653: WARNING: Literal block expected; none found.
/home/runner/work/METplus/METplus/docs/index.rst: WARNING: document isn't included in any toctree
/home/runner/work/METplus/METplus/docs/Contributors_Guide/add_use_case.rst:204: WARNING: undefined label: quick-search
```
I'll investigate these to see which may need to be fixed.

**Comment by ksearight** [comment]
Addressed 3 of the 5 warnings.  The HTML version was only building the User Guide, so I changed conf.py to specify a different root doc for HTML and PDF.  One of the remaining warnings is in the Release Guide (which I didn't touch) and the other is a type mismatch which doesn't make sense in my reading of the documentation and doesn't affect the build.

**Comment by ksearight** [comment]
Documentation workflow passed, so proceeding with the merge.

**Pull request merged**
