### PR TITLE
Feature 892 rmm omi tests

### LINKED ISSUE #892: New Use Case: RMM and OMI (driver scripts)
## Describe the New Use Case ##
Convert the example scripts (compute_omi_example.py, compute_rmm_example.py, phase_diagram_example.py)  into the METplus system as driver scripts using the UserScript command.  This will include running the model and obs through a MET tool to get a MET formatted netCDF and then reading in this with the new calcpy read_file.py

### Acceptance Testing ###
data is on kiowa:/d1/projects/METcalcpy/METcalcpy_Data/MJO_Indices

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] compute_omi_example.py
- [ ] compute_rmm_example.py
- [ ] phase_diagram_example.py
- [ ] fix data read-in for MET format and perhaps move read in to a separate utility script

### Relevant Deadlines ###
ASAP, METplus 4.1.0

### Funding Source ###
2785051

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] [METcalcpy Issue](https://github.com/dtcenter/METcalcpy/issues/89)
- [ ] [METplotpy Issue](https://github.com/dtcenter/METplotpy/issues/109)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Ran use cases through automation and ensured that all use cases ran successfully

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review new use case output for accuracy

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[Yes]**</br>
Once new output is confirmed to be accurate, we will need to update develop-ref to generate truth data for new cases.

- [X] Please complete this pull request review by **7/30/2021**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by CPKalb** [comment]
What is failing in the tests for this?  It's working fine on my end.

**Comment by georgemccabe** [comment]
> 
> 
> What is failing in the tests for this? It's working fine on my end.

@CPKalb the failures in the tests are from the difference test because there is new output from the new use cases that are not in the truth data. It fails to alert us that we need to update the reference branch (develop-ref) after this PR is merged so the new data is available in the truth data set for future difference tests. If the output data looks correct to you then we can approve this PR and update the reference branch.

**Comment by georgemccabe** [comment]
@CPKalb see the image below. If you click on one of the failing jobs in GitHub Actions (or click on the "Details" link under Checks in this PR) you would see that the failure occurs in the "Run difference tests" job. Towards the bottom of the log you will see a "Summary" that lists all of the differences that were found. You can see that all of the differences are from new output (B) that is not found in the truth data set (A). If those are the only differences, then the PR can be approved.

s2s-diff

**Review by hankenstein2 — COMMENTED** [review]
All the files look good and all the tests worked except for the new data tests.

**Review by CPKalb — COMMENTED** [review]
Works and produces expected output

**Pull request merged**
