### PR TITLE
Feature #2754 rc1_main_vX.Y

### LINKED ISSUE #2754: Documentation: Update Release Guide to create the main_vX.Y branch for the first release candidate
## Describe the Task ##
As discussed via Slack and during METplus project meetings, update the instructions in METplus Release Guide to create the main_vX.Y branches prior to the first release candidate rather than waiting for the official release. This change frees up the develop branch to accept new changes for future releases rather than needing to keep it locked down until the official release date.

The downside is that changes between RC1 and the final official release will need to be made to both the main_vX.Y branch and the develop branch.

### Time Estimate ###
2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
DTC NOAA Base (2782544) for software release support

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Note that I deleted the `push_release_branch.rst` instructions since it's not needed. The preceeding instructions execute the push and this is redundant - even for METplus which has custom instructions.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Ran `make clean html` to make sure the docs build.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please review updated docs for clarity and accuracy:
https://metplus.readthedocs.io/en/feature_2754_rc1_main_vx.y/Release_Guide/index.html

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [x] Please complete this pull request review by **[Wed 10/30/24]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METplus-Wrappers-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
I need to review this more closely, but I think the instructions get mucked up in terms of version numbers, at least for the METplus Development steps.

I think additional changes are needed to:
* In the METplus Development `Update Version Number for Release` step, we should not update the version number if creating an rc1 release. The version gets updated in the main_vX.Y-ref branch later and also gets updated in the develop branch later.
* In the METplus Development `Create Release Reference Branch` sub-step `Update the version number`, we may want to update the example to include an `-rc1` version since this step should only be run for that version.
* In METplus Development `Update Version on Develop Branch`, if we just created an rc1 release, the version number in develop should reflect development towards `beta1` for the next release after the one we are currently developing towards.

This may apply to other release instructions as well.

**Comment by JohnHalleyGotway** [comment]
I note that instructions reference a file named `docs/version`.

Checking the repos I see that:
- The METdataio version is defined in [METdataio/docs/version](https://github.com/dtcenter/METdataio/blob/develop/docs/version) as `3.0.0-rc1-dev`.
- The METcalcpy version is defined in [METcalcpy/docs/version](https://github.com/dtcenter/METcalcpy/blob/develop/docs/version) as `__version__="3.0.0-rc1-dev"`.
- The METplotpy version is defined in [METplotpy/docs/conf.py](https://github.com/dtcenter/METplotpy/blob/af7eecf8375a69b68c10b618d543ea8fdcfd565f/docs/conf.py#L25C1-L25C8) as `version = 'v3.0.0-rc1-dev'`.
- The METviewer version is defined in [METviewer/docs/conf.py](https://github.com/dtcenter/METviewer/blob/17b76eebffee018b67f1c82d20d2ac67d0f9907a/docs/conf.py#L23) as `version = "3.0.0-rc1-dev"`.
- The METplus version is defined in [METplus/metplus/VERSION](https://github.com/dtcenter/METplus/blob/develop/metplus/VERSION) as `6.0.0-rc1-dev`.
- The MET version is defined in [MET/src/basic/vx_util/util_constants.h](https://github.com/dtcenter/MET/blob/5c176a9b18f9c8dc39c759fa121fce6343fecfec/src/basic/vx_util/util_constants.h#L46) as `static const char * const met_version    = met_version_12_0_0;`

We have custom instructions for updating the version numbers for MET and METplus.
- The METdataio/METcalcpy instructions are correct, referring to `docs/version`.
- The METplotpy/METviewer instructions are INCORRECT since `docs/version` does not exist.

@jprestop and @bikegeek can you please review this situation and advise? Can we handle the version definition consistently across all the METplus-Analysis repositories? Or is there a good reason for them to be different?

**Comment by jprestop** [comment]
@JohnHalleyGotway I noticed these differences when I was cutting the releases and created this issue to try to make them more consistent [Update release notes for METplus components #2737](https://github.com/dtcenter/METplus/issues/2737).

**Comment by JohnHalleyGotway** [comment]
@georgemccabe thanks for taking a look. I did just update the METplus example to switch from `betaN` to `rc1`:
```
-  with -dev added to the end like X.Y.Z-betaN-dev, i.e. 4.0.0-beta1-dev
+  with -dev added to the end like X.Y.Z-rc1-dev, i.e. 4.0.0-rc1-dev
```
However, I don't really appreciate the intricacies of when/where you want `-dev` to be added/removed.

Please feel free to check out this feature branch and directly modify it to update the `-dev` handling instructions as needed.

**Comment by georgemccabe** [comment]
I made a number of changes to:
* Properly update the version numbers
* Select the appropriate branch for releases (betaN and rc1 vs. rc2+, main for official releases)
* Update the develop branch version number after creating an rc1 release

Note there is some duplication in the component-specific instructions for update_version_on_develop.rst that could be consolidated using variables, but I did not make those changes.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe I re-requested your review on this issue.

@jprestop can you please advise whether you'd like to proceed with these changes?

**Comment by georgemccabe** [comment]
@JohnHalleyGotway, I think it would be best if someone else reviewed the content since I made the last set of changes. @jprestop, could you review the changes?

**Comment by jprestop** [comment]
You bet!  I have some things I need to get done first but I'll review as soon as I can.

**Review by jprestop — APPROVED** [review]
I have reviewed the updated docs for clarity and accuracy.  It looks good to me. I have ensured all tests passed.  Thank you @JohnHalleyGotway and @georgemccabe for working through all of these details. I approve this request.

**Review by georgemccabe — APPROVED** [review]

**Pull request merged**
