### PR TITLE
Feature #2299 / #2310 Remove deprecated MET config env vars and TCMPRPlotter

### LINKED ISSUE #2299: Enhancement: Remove support for deprecated environment variables for old wrapped MET config files
Support for setting values in MET config files now follows a naming standard (environment variables start with METPLUS_). There is a lot of messy logic in the wrappers to continue supporting environment variables with the old naming conventions. This makes the code more complex than necessary and clutters the log output.

Many of these old variables have been supported since v4.1. We decided that this change should be made for a major release (X.0). We were unable to make this update for v5.0, so it would be good to complete it for v6.0.0. Ideally the changes would be made early in the development cycle (beta1?) so that testing can expose external use cases that reference old environment variables so they can be updated before the official release.

Users are urged to use the wrapped MET config file that is provided with the wrappers instead of using their own so that any updates to support new configs are automatically available. If they are using the provided files, then these changes will not affect them.

## Describe the Enhancement ##
Remove support for old environment variables in favor of the newer env vars that start with METPLUS_.

For example, this function in ascii2nc_wrapper.py:

```
    def set_environment_variables(self, time_info):
        """!Set environment variables that will be read by the MET config file.
            Reformat as needed. Print list of variables that were set and their values.
            Args:
              @param time_info dictionary containing timing info from current run"""
        # set environment variables needed for legacy MET config file
        self.add_env_var('TIME_SUMMARY_FLAG',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_FLAG', ''))
        self.add_env_var('TIME_SUMMARY_RAW_DATA',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_RAW_DATA', ''))
        self.add_env_var('TIME_SUMMARY_BEG',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_BEG', ''))
        self.add_env_var('TIME_SUMMARY_END',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_END', ''))
        self.add_env_var('TIME_SUMMARY_STEP',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_STEP', ''))
        self.add_env_var('TIME_SUMMARY_WIDTH',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_WIDTH', ''))
        self.add_env_var('TIME_SUMMARY_GRIB_CODES',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_GRIB_CODES', '').strip('[]'))
        self.add_env_var('TIME_SUMMARY_VAR_NAMES',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_VAR_NAMES', '').strip('[]'))
        self.add_env_var('TIME_SUMMARY_TYPES',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_TYPES', '').strip('[]'))
        self.add_env_var('TIME_SUMMARY_VALID_FREQ',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_VALID_FREQ', ''))
        self.add_env_var('TIME_SUMMARY_VALID_THRESH',
                         self.env_var_dict.get('METPLUS_TIME_SUMMARY_VALID_THRESH', ''))

        # set user environment variables
        super().set_environment_variables(time_info)
```

can be completed removed because setting the new environment variables are handled within the add_met_config functions.

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
v6.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### LINKED ISSUE #2310: Remove TCMPRPlotter wrapper
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Change Summary
* #2310 and related use cases
* #2299
  * Remove calls to set env vars that are deprecated (e.g. don't start with METPLUS_)
  * Change logic to validate MET config files to use list of deprecated env vars specific to each wrapper
  * Instruct users that have deprecated env vars in their MET config to use provided version of wrapped MET config and set values in METplus config instead.

#### Other Changes
* Fix bug in diff util that incorrectly reports the wrong column name when diffs are found in a stat file
* Changed use case to set MODEL and OBTYPE because default values are no longer used (to prevent diffs in test output)

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Ensured all tests pass

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

* Review code changes
* Verify all tests pass (no diffs)

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

I think so

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **9/15/2023**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [X] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
HI @georgemccabe. It sounds like you expected no differences, but the short_range:2-6 tests failed due to the following differences.  Are they acceptable differences?

```
**************************************************
Summary:


ERROR: Some differences were found
Text diff
A:/data/truth/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V_dmap.txt
B:/data/output/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V_dmap.txt

Text diff
A:/data/truth/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_010000L_20190521_010000V_dmap.txt
B:/data/output/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_010000L_20190521_010000V_dmap.txt

Text diff
A:/data/truth/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_010000L_20190521_010000V.stat
B:/data/output/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_010000L_20190521_010000V.stat

Text diff
A:/data/truth/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V.stat
B:/data/output/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V.stat

Finished comparing directories
**************************************************
```

**Comment by georgemccabe** [comment]
@jprestop, thanks for pointing that out. That is weird, because the diff results were different when I tested before the PR so I changed the use case to produce the results that are showing diffs now. FYI, there is an expandable tab above the diff summary that you can click to see the full diff results or you can just search for `ERROR` in the log file (search bar is above the log window, don't use the browser search). Below is one of the diffs. I'll push a change to the use case conf to prevent this diff.

> COMPARING short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V_dmap.txt
>   file_A: /data/truth/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V_dmap.txt
>   file_B: /data/output/short_range/GridStat_fcstFV3_obsGOES_BrightnessTempDmap/short_range/brightness_temperature/grid_stat/grid_stat_FV3_core_lsm1_020000L_20190521_020000V_dmap.txt
>   
>   Using default rounding precision 6
>   Comparing text files
>   Comparing stat files
>   ERROR: Stat line differs
>   A: V12.0.0 WRF   NA   020000    20190521_020000 20190521_020000 000000   20190521_020000 20190521_020000 SBTA1613_topofatmosphere K          top_of_atmosphere channel_13_brightness_temperature NA        *,*     ANALYS FULL    NEAREST     1           <=235       <=235      NA         NA    DMAP      1701276 149369 151257 0.98752 60.47303 251.28669 8.00318 4.40839 4.40839 8.00318  6.20578 0.70706 0.7464 0.70706  0.7464  0.72673 4.12716 2.32976 2.32976 4.12716  3.22846 5853.38045 0.86142 1447170014088
>   B: V12.0.0 FCST  NA   020000    20190521_020000 20190521_020000 000000   20190521_020000 20190521_020000 SBTA1613_topofatmosphere K          top_of_atmosphere channel_13_brightness_temperature NA        *,*     OBS    FULL    NEAREST     1           <=235       <=235      NA         NA    DMAP      1701276 149369 151257 0.98752 60.47303 251.28669 8.00318 4.40839 4.40839 8.00318  6.20578 0.70706 0.7464 0.70706  0.7464  0.72673 4.12716 2.32976 2.32976 4.12716  3.22846 5853.38045 0.86142 1447170014088
>   
>   Diff in MODEL:
>   A: WRF
>   B: FCST
>   Diff in OBTYPE:
>   A: ANALYS
>   B: OBS

**Comment by georgemccabe** [comment]
@jprestop, on second though, WRF is not a good value to have here because the forecast data is not WRF. I think we can accept these diffs and update the truth data instead. What do you think?

**Review by jprestop — APPROVED** [review]
I have reviewed the code changes and have ensured that all but one of the tests passed. There are a lot of changes here.  Thanks for all of your work on this @georgemccabe.  I very much agree that WRF is not a good value to have here because the forecast data is not WRF. I agree that we should accept these diffs and update the truth data instead.  I approve this request.

**Pull request merged**
