### PR TITLE
Feature 536 multiple diagnostics

### LINKED ISSUE #536: Enhance User Diagnostic Feature Relative use case to Run Multiple Diagnostics
## Describe the Enhancement ##
The user diagnostic feature relative use case only runs on one diagnostic. This enhancement will set up the use case to allow users to run this use case on as many diagnostics as they provide. Related to #522 

### Time Estimate ###
2 days

### Sub-Issues ###
- [x] Test user provided diagnostic script (calculates potential vorticity)
- [x] Add PyEmbedIngest commands/configurable options for second diagnostic
- [x] Run use case to make sure it produces statistics for both diagnostics
- [x] Confirm output of new use case matches original output
- [x] Add use case documentation
- [x] Update model data included in tarball to have the variables required to calculate PV.
- [x] Add an image  for the UG.

### Relevant Deadlines ###
NONE

### Funding Source ###
Stony Brook University

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: No engineer required
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
#522 

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by lindsayrblank**
Created a new feature relative use case (TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.conf) that uses the output of a user diagnostic python script to run SeriesByLead on. This use case allows users to run the feature relative user provided diagnostic use case on as more than one diagnostic and includes new python scripts for the second diagnostic. 

#536 
#522

### CODE REVIEW

**Comment by georgemccabe** [comment]
@lindsayrblank the destination of this PR should be develop, not master_v3.1

**Comment by lindsayrblank** [comment]
@georgemccabe Thank you! I completely missed that. I fixed it.

**Comment by georgemccabe** [comment]
Great, thanks! I was hoping you didn't have to change 200+ files to get your use case added!

Once @JohnHalleyGotway has updated the Docker data volumes, I can add these new use cases to the Travis tests to ensure that they run successfully. Question: @lindsayrblank , do the new use cases also require the additional python packages that are required by the last feature relative use case you added? Are there any other new dependencies?

**Comment by lindsayrblank** [comment]
@georgemccabe Thankfully, no, only a few files. No, there are no new python dependencies that I'm aware of.

**Comment by georgemccabe** [comment]
@lindsayrblank I see 2 new conf files in the repo:

TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_Multiple_Diagnostics.conf
TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.conf

Are both of these files needed? It looks like the first one also uses PyEmbed so I thought I should check.

**Comment by lindsayrblank** [comment]
@georgemccabe Hi George, only one is needed, the TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.conf is the correct one. I deleted the other one locally. Is there a way to push deletions to the remote branch?

**Comment by georgemccabe** [comment]
@lindsayrblank , yes, just use "git rm <filename>" to remove it, then commit and push your changes. If you push to this branch it will automatically update this pull request.

**Comment by georgemccabe** [comment]
The tests passed! Merging this into develop.

**Pull request merged**
