### PR TITLE
Bugfix #1853 develop - PointStat don't require mask variables to be set

### LINKED ISSUE #1853: Bugfix: PointStat - Support running with no MASK provided
## Describe the Problem ##
If you have `PointStat` in the `PROCESS_LIST` but provide no mask information, the `mask{}` dictionary in the MET config file will be empty and cause `point_stat` to return an error.

This is happening because of the way the mask dictionary is set via environment variables.

```
mask = {
   ${METPLUS_MASK_GRID}
   ${METPLUS_MASK_POLY}
   ${METPLUS_MASK_SID}
   //llpnt =
   ${METPLUS_MASK_LLPNT}
}
```

If no mask values are set, then the result is `mask = {}` which throws an error when MET is parsing the config files. The logic should be refactored to instead set ${METPLUS_MASK_DICT}.

As a workaround, users can set `POINT_STAT_MASK_GRID = FULL` to get the same behavior as the default.

### Expected Behavior ###
If the user does not set any of the `*_MASK_*` variables when using `PointStat`, then PointStat should still run using the default mask dictionary values.

### Environment ###
Describe your runtime environment:
1. Running on seneca

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Added new unit tests to ensure correct behavior. Ran PointStat.conf basic use case example with a variety of settings to ensure the correct behavior is possible

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Test existing use case to ensure it can now be configured as expected

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
New/updated unit tests but they should all pass

- [X] Please complete this pull request review by **7/27/2023**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by DanielAdriaansen — CHANGES_REQUESTED** [review]
Is the `__init__.py` file needed?

**Comment by georgemccabe** [comment]
@DanielAdriaansen, no. That is why it was removed. I don't know why it was added there in the first place.

> Is the `__init__.py` file needed?

**Comment by DanielAdriaansen** [comment]
> @DanielAdriaansen, no. That is why it was removed. I don't know why it was added there in the first place.
> 
> > Is the `__init__.py` file needed?

Sorry I misinterpreted the "Files Changed" view. I did not notice the file was 'deleted' but rather just noted it said "empty file" and so thought we were adding an empty file but in reality it has been deleted. Sorry about that.

**Review by DanielAdriaansen — APPROVED** [review]
I tested on Seneca using the met_tool_wrapper/PointStat.conf file. In that file, I commented out these lines:
```
#POINT_STAT_MASK_GRID = DTC165, DTC166
#POINT_STAT_MASK_POLY = MET_BASE/poly/LMV.poly
#POINT_STAT_MASK_SID =
#POINT_STAT_MASK_LLPNT =
```

When using `run_metplus.py` from the develop branch, this causes a failure reported by `point_stat`. When I use `run_metplus.py` from this branch, `point_stat` succeeds.

Thanks @georgemccabe!

**Pull request merged**
