### PR TITLE
Feature 662 vx_data

### LINKED ISSUE #662: Add a new document for METplus to inventory verification datasets for MET and METplus.
## Describe the Enhancement ##
This task relates to the 2019 Air Force datasets project for which we had a kickoff meeting on 10/14/21.

This task consists of the following steps:
- Add a new METplus document to describe input verification datasets (e.g. point observations, gridded verifying analyses, and gridded forecast products).
- Develop a template that can be used to describe each dataset. For that template, consider including:<br/>
description, type (point vs grid), file format, date, availability (public/private), scientific motivation for use in vx, pointer to python embedding scripts
- Ideally each dataset would be demonstrated by a METplus use case, and the template would point to that use case example.
- If that's not possible, then at least create an example of plotting the data through METplus. But where should that sample python script and input file live?
- Survey the DTC testing and evaluation projects as widely as possible to capture as many datasets as are feasible.
- Update the existing directions for "adding a new use case" to instruct developers to check/update this new document with novel datasets.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
Merging in initial version for METplus version 4.0.0-beta2, but created a separate METplus #715 issue to develop additional content.

### Relevant Deadlines ###
The funding for this task ends at the end of January 2021.
This work should be completed by the METplus-4.0-beta3 release, which is tentatively scheduled for 1/18/21.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle Harrold to review PR.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Pull Request Testing ##

This is the initial version of the verification datasets document. @michelleharrold please review the content.  @jprestop please review the structure.

- [x] Describe testing already performed for these changes:</br>
Please find rendered html tarfile for review here:
ftp://ftp.rap.ucar.edu/incoming/irap/met_help/feature_662/feature_662_vx_data_html.tar.gz

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
Untar and review the html content.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Review by jprestop — COMMENTED** [review]
I like the overall structure, but am confused about something.  When I view the "by" pages (e.g. by-application, by-level, etc.) the menu is different from when I view the index page.  Is that to be expected?  Hopefully the images below will come through...
image

image

**Comment by JohnHalleyGotway** [comment]
Julie, I had started with separate pages for by-type, by level, by provider, and by application. But I later decided to consolidate them down into a single quick search chapter... following the existing convention of the METplus User's Guide. So I want the latter menu options, and not the former.

**Review by jprestop — APPROVED** [review]
Awesome!  Thanks.  I prefer the latter option too.  Thanks!  I reviewed the structure and approve.

**Comment by michelleharrold** [comment]
@JohnHalleyGotway this looks great! (Much cleaner and more of a template than my google doc...). One thing:

On the main index page, I see this:
Screen Shot 2020-12-03 at 12 43 06 PM

When I click on the Overview, I see this:
Screen Shot 2020-12-03 at 12 43 21 PM

--> 2. Datasets from from index page became 2. Quick Search for Datasets, and Datasets is gone.

**Comment by JohnHalleyGotway** [comment]
Michelle, great, thanks for taking a look. I fixed that menu item issue by removing some stale links in this commit:
https://github.com/dtcenter/METplus/pull/709/commits/326a5fa812306658b2f5c8badf0f38b643e114cc

I didn't update the html pages you reviewed, but rest assured it is fixed. Do you know how to submit a PR review approval instead of just comment? One way is to click on the "Files Changed" tab, click the "Review Changes" green button in the top-right corner, and select the "Approve" radio button with whatever comments you like. That'll add a little green checkbox indicating you review

**Review by michelleharrold — APPROVED** [review]

**Pull request merged**
