### PR TITLE
feature #2253 more tests for diff_util.py

### PR DESCRIPTION
**Pull request by John-Sharples**
In this commit:

- updated `create_diff_files` to use pytest fixture for creating temporary files, as discussed in a previous PR.
- added one test case to `test_diff_dir_text_files` for when float trunc and round are not the same
- new tests for `_handle*` functions
- new test for `compare_image_files` - note this only compares 1x1 pixle images, so scope for expansion on this one
- new small test for when `netCDF4.Dataset` is used to determine file type.
- ran `black` over the test file (makes the diff a little harder to read, sorry)

There are a few more functions that could easily be added if `numpy` is available (e.g. `_all_values_are_equal`). However, not wanting to add an extra depedancy. 

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tests all passing locally

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
None

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation?
Yes

- [x] Do these changes include sufficient testing updates? 
Yes

- [x] Will this PR result in changes to the test suite? </br>
Yes - more tests will run for diff_util.py </br>

- [x] Please complete this pull request review by ... whenever you have time.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: @georgemccabe 
Select: 
Select:
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
It looks like there is an argument to `black` to skip changing all single quotes to double quotes.

https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#s-skip-string-normalization

Could you rerun black with this option to skip these changes?

I would like to discuss adopting the use of double quotes for all strings with the team before making a decision on this style change. We have used single quotes for strings throughout the METplus code.

My biggest concern with this change is it will make diffs/blames much harder to follow. If we do decide to adopt this style, I think I would like to reformat the entire code base with these changes in a single commit so that the commit can be ignored if needed. Still, I'm not sure if it is possible to ignore a commit in the GitHub web interface.

**Comment by John-Sharples** [comment]
My apologies! I thought `black` was listed as a preferrd formatter in the Contributor's Guide, but now that I read it more closely I must have imagined that. I've rolled back the black changes and rebased onto `develop` again. 

Thanks for letting me know about the preference for single quotes too. I'll keep that in mind for future PRs.

**Comment by georgemccabe** [comment]
I should clarify that while I personally tend to prefer using single-quotes, we don't have a hard rule to use single or double quotes for new code. We just don't want to convert existing code to use double quotes. I mainly want to avoid cluttering up the diff/blame with these changes that are cosmetic. @bikegeek mentioned something about double quoted strings cluttering up docstring output as well.

Thank you for cleaning up your changes!

**Review by georgemccabe — APPROVED** [review]
These changes look good. I see you cleaned up my tests to use the built-in fixture tmp_path_factory to create temporary files to be consistent and added tests for other file types. Thank you!

FYI, numpy is available to use in the tests. It looks like it is installed as a dependency of pandas when installing via conda.

**Pull request merged**
