### PR TITLE
Feature 628 diff index

### LINKED ISSUE #628: Add Difficulty Index use-case for NRL transitioned capability
## Describe the New Feature ##
The Difficulty Index is now transitioned to METcalcpy and METplotpy. Now, the DTC needs to add a METplus use case that produces the Difficulty Index using these capabilities. 

Here is a description of the Difficulty Index from NRL:
"The overall aim of this work is to graphically represent the expected difficulty of a decision based on a set of forecasts (ensemble) of, e.g., significant wave height as a function of space and time. There are two basic factors that can make a decision difficult. The first factor is the proximity of the ensemble mean forecast to a decision threshold, e.g. 12ft seas. If the ensemble mean is either much lower or much higher than the threshold, the decision is easier; if it is closer to the threshold, the decision is harder. The second factor is the forecast precision, or ensemble spread. The greater the spread around the ensemble mean, the more likely it is that there will be ensemble members both above and below the decision threshold, making the decision harder. The challenge is combing these factors into a continuous function that allows the user to assess relative risk."

### Acceptance Testing ###
Model data: NCEP WaveWatch III data

Tests Required for new functionality: 
Outputs needs to match the output provided by NRL original code. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
3 working days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] Identify tools: None
- [x] Request new sample data from NRL
- [x] Figure out what category this use case falls under: medium range
- [x] Meet with George, Hank, and Minna about how to approach this
- [x] Reproduce wind output
- [x] Add pytest?

### Relevant Deadlines ###
January 18, 2021

### Funding Source ###
NRL - 2700021

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: George McCabe
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

https://github.com/dtcenter/METcalcpy/issues/27
https://github.com/dtcenter/METcalcpy/issues/37
https://github.com/dtcenter/METplotpy/issues/47

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Ran the METplus use case on kiowa. It ran successfully.

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
Reviewers should run UserScript_fcstGEFS_Difficulty_Index.conf and make sure it runs successfully for them. 
Reviewers should also skim the documentation and make sure nothing is obviously wrong.

- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Unknown

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes or No]**</br>
Yes

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Comment by lindsayrblank** [comment]
@bikegeek George and I need someone who hasn't developed this code to review it, which is why I assigned you. Let me know if you have any questions.

**Review by lindsayrblank — APPROVED** [review]
It all worked for me, but I made a lot of changes so someone else needs to review it.

**Comment by georgemccabe** [comment]
@lindsayrblank  the use case is now failing because the run time was changed and it no longer matches the data that was put on the DTC web server. The previous run time was 2020121100 and it is now set to 2020120812. Why was this time changed? If it was by mistake, we can change it back in the .conf file and the test should succeed again.

**Review by bikegeek — CHANGES_REQUESTED** [review]
1) Typo in the Scientific Objective section, last sentence:
_The challenge is combing these factors into a continuous function that allows the user to assess relative risk._

**Replace combing with combining**

2) Under the Datasets section, what are the hash tags in the following supposed to represent?

_Variables required to calculate the difficulty index: Levels required: 10-m #. v- component of wind #. u- component of wind #. Windspeed #. Latitude #. Longitude_

3) Running master_metplus.py, I had to set the PYTHONPATH to include the path to METcalcpy, but there aren't instructions for how to set this in the documentation.  Likewise for METplotpy.

4) Running master_metplus.py I see in the log file that there is a module not found error for 'matplotlib'.  I didn't see any instructions in the documentation for installing the matplotlib library

**Comment by georgemccabe** [comment]
I am addressing some of these comments inline:

> 
> 
>     1. Typo in the Scientific Objective section, last sentence:
>        _The challenge is combing these factors into a continuous function that allows the user to assess relative risk._
> 
> 
> **Replace combing with combining**
>

This change makes sense to me.

>     1. Under the Datasets section, what are the hash tags in the following supposed to represent?
> 
> 
> _Variables required to calculate the difficulty index: Levels required: 10-m #. v- component of wind #. u- component of wind #. Windspeed #. Latitude #. Longitude_
> 

My guess is the hash tags are meant to create a numbered list. This is RST syntax. However, I have had issues in the past getting this to work in other situations. If the hash tags do not render as numbers when building the docs, I would suggest just changing these to the actual numbers since this list is unlikely to change often (if ever).

>     1. Running master_metplus.py, I had to set the PYTHONPATH to include the path to METcalcpy, but there aren't instructions for how to set this in the documentation.  Likewise for METplotpy.
> 
>     2. Running master_metplus.py I see in the log file that there is a module not found error for 'matplotlib'.  I didn't see any instructions in the documentation for installing the matplotlib library

For the last 2 items, I noticed that very few use case documentation files contain information about additional external dependencies. We should create a GitHub issue to review all of the use cases that require additional python packages used for python embedding scripts and add an "External Dependencies" section to the docs that describe what is needed to run. We should also make sure the python embedding scripts are added to the use case doc with a literalinclude. The use cases that I see have an "External Dependencies" section already are:

* model_applications/precipitation/GridStat_fcstHREFmean_obsStgIV_Gempak.py
* met_tool_wrapper/GempakToCF/GempakToCF.py
* /met_tool_wrapper/PCPCombine/PCPCombine_python_embedding.py

so there are many that need to be updated.

In terms of instructions to install the packages or adding to the PYTHONPATH to make the packages found, in my opinion our responsibility is to list the packages that are needed and it is up to the user to obtain and install them. Most of the packages have documentation that describes how to install them with pip or conda. Are there installation instructions for METplotpy and METcalcpy? If not, that would be helpful to users.

**Comment by georgemccabe** [comment]
I created a new GitHub issue to add all extra Python dependencies to use case docs: #767

**Comment by lindsayrblank** [comment]
> @lindsayrblank the use case is now failing because the run time was changed and it no longer matches the data that was put on the DTC web server. The previous run time was 2020121100 and it is now set to 2020120812. Why was this time changed? If it was by mistake, we can change it back in the .conf file and the test should succeed again.

Hi George, I had miscalculated the initialization date when naming the input file. I realized this when writing the documentation. I forgot to apply the local filename change to the tarball.

**Comment by lindsayrblank** [comment]
> 1. Typo in the Scientific Objective section, last sentence:
>    _The challenge is combing these factors into a continuous function that allows the user to assess relative risk._
> 
> **Replace combing with combining**
> 
> 1. Under the Datasets section, what are the hash tags in the following supposed to represent?
> 
> _Variables required to calculate the difficulty index: Levels required: 10-m #. v- component of wind #. u- component of wind #. Windspeed #. Latitude #. Longitude_


Thank you for your review, Minna. I have fixed the typo you found and hopefully the numbered list builds correctly. I have used it in other use case documentation in the past, so it should theoretically work.

**Comment by georgemccabe** [comment]
Once the input data is updated, the conf file is updated to use the correct time, and all of the tests pass, we can merge these changes.

**Comment by lindsayrblank** [comment]
> Once the input data is updated, the conf file is updated to use the correct time, and all of the tests pass, we can merge these changes.

I updated the input data and the conf file. It looks like the tests run after I made those changes have passed. I think we're good!

**Pull request merged**
