### PR TITLE
feature 625 JEDI StatAnalysis use case

### LINKED ISSUE #633: Add stage to Travis to update or create data volumes when new sample data is available
Full notes here: https://docs.google.com/document/d/1aiXzap39K2pU2WQB3VAkJnlNN1WKVOixpcZdhEUYe2Y/edit#heading=h.skvq0sd9rdg8

## Describe the Enhancement ##
Compare last modified time of tarfiles hosted on web server.
Check if docker data volume already exists
If it exists, compare creation time to tarfiles to determine if they need to be rebuilt.
If it doesn't exist, create the data volumes
Push the new volumes

### Time Estimate ###
3+ days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Write scripts to check times on web and DockerHub*
- [ ] *Set up credentials to push to DockerHub*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### LINKED ISSUE #636: Enhance the build_docker_images.sh script to support TravisCI updates.
## Describe the Enhancement ##
The METplus team is overhauling the logic for preparing input datasets for continuous integration testing with Travis. That overhaul is described in this Google Doc:
https://docs.google.com/document/d/1aiXzap39K2pU2WQB3VAkJnlNN1WKVOixpcZdhEUYe2Y/edit

Listed below are the specific changes related to the build_docker_images.sh script.

- [x] (1) Enhance build_docker_images.sh to support the following usage statement:
```
Usage: build_docker_images.sh
        -pull version
        [-dataset list]
        [-union]
        [-push repo]

        where:
          "-pull version" defines the version of the datasets to be pulled (required).
          "-dataset list" overrides the use of all datasets for this version with a comma-separated list (optional).
          "-union" also creates one data volume with all datasets for this version (optional).
          "-push repo" pushes the images to the specified DockerHub repository (optional).

  e.g. Pull from https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/<version>
       Push to DockerHub <repo>:<version>-<dataset>
```
- [x] (2) Delete the metplus_sample_data ascii file.
- [x] (3) Use “curl” to get a list of tarfiles to be processed for the requested version.
```
curl -s https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/develop/ | tr "<>" "\n" | grep sample_data | egrep -v href
```
Make sure to ignore the optional "-version" at the end of the tarfile name.
- [x] (4) Enhance the Dockerfile to search for a hidden ".VOLUME" file which specifies the directory that should be used as the VOLUME mount. 
- [x] (5) Update each existing tarfile by adding a hidden file named “.VOLUME” in the directory that should be mounted in the Dockerfile, i.e. model_applications/<category>/.VOLUME
Enhance that script to find the hidden “.VOLUME” file and define that directory as the mount point.
- [x] (6) Change ${MOUNTPT} from being a required Dockerfile argument to optional. If supplied (as in the union of tarfiles), use it. If not, find .VOLUME in the tarfile. If not found, exit with a useful error message.
- [x] (7) Update the build hooks files to run:
```
./build_docker_images.sh -pull $SOURCE_BRANCH -union -push dtcenter/metplus-data
```
- [x] (8) Update the DockerHub automated builds for dtcenter/metplus-data to ONLY build tagged version numbers, not the develop branch. Also delete the dtcenter/metplus-data:develop* images since the develop images will now live in metplus-data-dev.
- [x] (9) On mohawk, double-check to ensure that all version directories contain a full listing of tarfiles or links for all required input datasets.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] #648 Reorganize use case tests so users can add new cases easily

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John HG
- [X] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
METplus #633 updates the TravisCI logic. These changes should be coordinate with those. No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
Many changes in the PR are related to GitHub issue #633. @JohnHalleyGotway and @fentoad72 , please provide any feedback related to the code changes for Travis/Docker.

I used this use case to test the new functionality to update and use new sample data. I included @TaraJensen and @willmayfield on this PR so you can review the use case documentation webpage and suggest any edits such as renaming files or tweaking the use case configuration. You can temporarily view the rendered doc page here:

http://icculus.rap.ucar.edu/metplus-test/generated/model_applications/tc_and_extra_tc/StatAnalysis_fcstHAFS.html#sphx-glr-generated-model-applications-tc-and-extra-tc-statanalysis-fcsthafs-py

### CODE REVIEW

**Comment by TaraJensen** [comment]
I haven't looked at the documentation but from the path to it, it seems like the naming of the Use-Case needs to be updated.  I'm sorry if my Slack message didn't get through, but it would be better to add this use-case to a new model application directory named data_assimilation.  The use-case should likely be named StatAnalysis_fcstHAFS_obsPrepBufr_JEDI_IODA_interface.conf

There should be a tags for tc-and-extra-tc-statanalysis-fcsthafs-py, and NOAA EMC

**Comment by georgemccabe** [comment]
@TaraJensen , I am making the changes you suggested. This will help refine the process for adding a new model applications category.

**Comment by fentoad72** [comment]
I'll defer to Tara on naming conventions.  I'm watching build #1117 and it
appears to be working.  I noticed you've done some changes to travis.yml
and use of the cache that seem to have sped things up.

Once the build completes I'll approve the PR, unless I should wait until
you've made the changes she suggested (like if you have to submit another
PR build).

== todd

=============================================================
Todd Arbetter
Research Applications Laboratory (RAL)
National Center for Atmospheric Research (NCAR)
arbetter@ucar.edu
303-497-2472

**Comment by georgemccabe** [comment]
@fentoad72 , I just pushed a new set of changes to rename the files based on @TaraJensen 's recommendations. This is the first time we are adding a new model applications category since these changes, so we should wait to approve until the new Travis builds succeed.

**Comment by fentoad72** [comment]
Sounds good.

=== todd

=============================================================
Todd Arbetter
Research Applications Laboratory (RAL)
National Center for Atmospheric Research (NCAR)
arbetter@ucar.edu
303-497-2472

**Comment by georgemccabe** [comment]
I am going to merge this into develop so we can get the changes needed for adding new use cases. We can still rename or change the JEDI use case if we need to later. I will leave the issue (#537) for the use case open until we are satisfied with the content.

**Pull request merged**
