### PR TITLE
update release guide instructions for updating DTC webpage

### PR DESCRIPTION
**Pull request by georgemccabe**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>
Added logic to build the documentation and make it available via GitHub Actions as an artifact and easily check for warnings

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

View this GHA run and note that there is an artifact called documentation_warnings.log that lists the warnings from the run. 

https://github.com/dtcenter/METplus/actions/runs/618083708

Note that artifact called METplus_documentation contains the HTML output of the documentation. The warning file should also be inside that tarfile.

Navigate to is next GHA run:
https://github.com/dtcenter/METplus/actions/runs/618329811

Download the METplus_documentation artifact, unzip it, open index.html in a browser, the navigate to the Release Guide to ensure the changes look OK. Note that no artifact named documentation_warnings.log was created.

Also notice that adding ci-doc-only to my last commit message caused the GHA run to only run the documentation step.

- [X] Do these changes include sufficient documentation and testing updates? **[Yes]**

Unless changes to the new Release Guide content are desired

- [X] Will this PR result in changes to the test suite? **[Yes]**</br>

The documentation output will now be available as an artifact.

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [X] After submitting the PR, select **Linked Issues** with the original issue number - no issue
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — COMMENTED** [review]
In Slack you mentioned:

> For METplus is says:
For Related Community Code select both the METplus and the METplus options (use shift to select).
It should say METplus Wrappers for one of them.

but I don't see any changes to that here.

I do not think we should have text that says "If creating a MET release" and "If creating a release for a project other than MET", but instead creating a generic page and a separate page for MET as is done with other pages.

For the bullet point "Click on Add Code Download then click Add Link to add links for each of the following:", the steps that start with "Add Link" should be indented under that bullet point.

**Comment by georgemccabe** [comment]
> 
> 
> In Slack you mentioned:
> 
> > For METplus is says:
> > For Related Community Code select both the METplus and the METplus options (use shift to select).
> > It should say METplus Wrappers for one of them.
> 
> but I don't see any changes to that here.
> 
> I do not think we should have text that says "If creating a MET release" and "If creating a release for a project other than MET", but instead creating a generic page and a separate page for MET as is done with other pages.
> 
> For the bullet point "Click on Add Code Download then click Add Link to add links for each of the following:", the steps that start with "Add Link" should be indented under that bullet point.

Ah, right. I missed the change for adding METplus Wrappers. So there should be 3 pages: 1 for MET with instructions to handle the tar file, 1 for METplus to explicitly write "METplus Wrappers", and 1 for the rest?

**Comment by jprestop** [comment]
That sounds correct to me.

**Review by jprestop — CHANGES_REQUESTED** [review]
After talking about the structure of these files via Slack with @JohnHalleyGotway and @georgemccabe, I think a single file for all METplus components with a specific one for MET would be best because that is the approach we've taken for other cases and it is less complex. @georgemccabe mentioned "For the "METplus" vs. "METplus Wrappers" we could have |projectName| that is set to |projectRepo| for the rest and "METplus Wrappers" for METplus so that we can use that to substitute." and I think that would be fine.  @georgemccabe also mentioned "I wonder if we could even set a variable to a block of text so we could override that whole block of text for MET in a variable?"  I think that is not necessarily necessary since we have other files for the various repositories that differ from the generic version, but if you would like to explore that, that is also fine.  I can see where that could be useful.

**Comment by georgemccabe** [comment]
@jprestop because the content of the doc is now correct, I suggest we use these changes and create a new issue to address reformatting of this doc, unless you can make these changes now. I have a list of things I need to complete for the upcoming release and can't dedicate more time now to updating this internal doc.

**Comment by jprestop** [comment]
It didn't seem like a good idea to create a new issue to address reformatting of this doc, so I delayed the ReadTheDocs and other work in favor of just getting this done now.  

I viewed the https://github.com/dtcenter/METplus/actions/runs/618083708  GHA run and note that there is an artifact called documentation_warnings.log that lists the warnings from the run. I noted that artifact called METplus_documentation contained the HTML output of the documentation. The warning file was also inside that tar file, as expected.  I navigated to the next GHA run:
https://github.com/dtcenter/METplus/actions/runs/618329811
I download the METplus_documentation artifact, unzipped it, opened index.html in a browser, navigated to the Release Guide to ensure the changes looked OK and noted that no artifact named documentation_warnings.log was created. I also noticed that adding ci-doc-only to your last commit message caused the GHA run to only run the documentation step.

However, my last commit message also contained "ci-doc-only" and it looks like the documentation step was not the only one that ran.  I thought I only needed to mention in it the commit message which I did with "Modified structure and formatting of the documentation ci-doc-only".  Did I do something in correct in my commit message?

**Comment by georgemccabe** [comment]
@jprestop I see 2 runs that have ci-doc-only that both only ran the docs:

https://github.com/dtcenter/METplus/actions/runs/622879414
https://github.com/dtcenter/METplus/actions/runs/622852798

This includes the one you mentioned: "Modified structure and formatting of the documentation ci-doc-only"

I'm not seeing any runs with ci-doc-only that ran everything else?

**Comment by jprestop** [comment]
Thanks for those links!  I was looking at this:
https://github.com/dtcenter/METplus/actions/runs/622879524

which looks like it was triggered at the same time as this:
https://github.com/dtcenter/METplus/actions/runs/622879414

**Review by jprestop — APPROVED** [review]
I approve this request.

**Pull request merged**
