### PR TITLE
create 4.0.0-beta5 release

### LINKED ISSUE #895: Create the METplus v4.0.0-beta5 release
Create the release by following the Release Guide instructions for a development release.

https://metplus.readthedocs.io/en/develop/Release_Guide/metplus_development.html

### PR DESCRIPTION
**Pull request by georgemccabe**
**NOTE: Open pull requests #889 and #891 should be merged into develop before merging this pull request!**

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

* Reviewed HTML documentation 

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

* Review release notes with bolded items (priority) and comment if any adjustments should be made.
https://metplus.readthedocs.io/en/feature_895_create_4.0.0-beta5_release/Users_Guide/release-notes.html

* Confirm GitHub Actions Documentation Workflow shows a red failure if there are documentation warnings and green success if there are none.
Failed: https://github.com/dtcenter/METplus/actions/runs/790296275
Success: https://github.com/dtcenter/METplus/actions/runs/790517821

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
Technically yes, I slightly changed the Documentation Workflow to report a failure if there are any warnings in the documentation, but no differences or errors should occur for the final review.

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [X] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — COMMENTED** [review]
I reviewed release notes with bolded items (priority), and while I thought they seemed like good choices to bold, @TaraJensen is likely the better person to indicate if any adjustments should be made.

Regarding:
> Confirm GitHub Actions Documentation Workflow shows a red failure if there are documentation warnings and green success if there are none.
> Failed: https://github.com/dtcenter/METplus/actions/runs/790296275
> Success: https://github.com/dtcenter/METplus/actions/runs/790517821

I don't really understand why there are two documentation workflows, one that fails and one that doesn't.  I see that there are two, but I'm not really sure what's going on there or what I should be checking.

**Comment by georgemccabe** [comment]
> I don't really understand why there are two documentation workflows, one that fails and one that doesn't. I see that there are two, but I'm not really sure what's going on there or what I should be checking.

@jprestop the failed documentation workflow was from a previous run. The successful run should be the most recent run. I noticed that there was a warning in the docs after I resolved a conflict because GitHub excluded a line break when I opted to use changes from both sides of the conflict. I decided to fix the documentation workflow to report an actual failure before fixing the doc since it seemed to be an opportune time to do it.

**Review by jprestop — APPROVED** [review]
I verified that there are no documentation warnings in the most recent run which was successful. I noted that there was a previous failure reported from the documentation run because GitHub excluded a line break when George used changes from both sides of the conflict, that he subsequently fixed.  I approve this request, but again, I am likely not the best person to advice on any changes to the bolding of the release notes.

**Comment by georgemccabe** [comment]
I am not sure where to put the list of default values that were incorrect in the wrapped MET config files (differ from the defaults in the MET share/met/config directory). Here is a list of the changes:

PointStat

interp.type.method
- was BILIN
- now NEAREST

POINT_STAT_INTERP_TYPE_METHOD = BILIN

interp.type.width
- was 2
- now 1

climo_mean.time_interp_method
- was NEAREST
- now DW_MEAN

obs_quality_flag
- was [ "1", "2", "3" ];
- now [];

PB2NC

pb_report_type
- was [120, 220, 221, 122, 222, 223, 224, 131, 133, 233, 153, 156, 157, 180, 280, 181, 182, 281, 282, 183, 284, 187, 287];
- now [];

level_category
- was [0, 1, 4, 5, 6];
- now [];

**Pull request merged**
