### PR TITLE
Feature #2433 Ugrid config variables in GridStat/PointStat

### LINKED ISSUE #2433: Enhancement: Point-Stat and Grid-Stat wrappers UGRID updates
## Describe the Enhancement ##
Issue dtcenter/MET#2231 and pull request dtcenter/MET#2723 adds support for reading unstructured grid information from NetCDF input files. Three new configuration options are added to both the Point-Stat and Grid-Stat default configuration files. This issue is to enhance those wrappers to add support for them.
- `ugrid_max_distance_km` = 30;
- `ugrid_user_map_config`: to override metadata settings (dimension and variable names)
- `ugrid_coordinates_file`: to specify the static metadata file (for MPAS)

I note that these new config options were *NOT* documented well in the MET User's Guide.

Issue dtcenter/MET#2748 requests that @hsoh-u add documentation about these options and support @georgemccabe in updating METplus wrappers to set them.

### Time Estimate ###
4 hours?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
Ideally do this during the METplus-6.0.0-beta3 development cycle.

### Funding Source ###
2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required
Recommend @georgemccabe doing the work and asking @jvigh to review the resulting PR.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
Also moved the seeps variable up so that it matches the order of the default config files in the MET repo

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Added unit tests

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Test that new settings work as expected in an example use case.

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **3/25/2024**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by DanielAdriaansen** [comment]
Testing summary so far:

### Test 1
```
POINT_STAT_UGRID_DATASET=lfric2
POINT_STAT_MAX_DISTANCE_KM=30
POINT_STAT_UGRID_COORDINATES_FILE=/home/dadriaan/projects/ugrid/data/fcst/lfric/20240112_ftp/lfric_2021-07-28_00.00.00.nc
POINT_STAT_UGRID_CONFIG_FILE=/home/dadriaan/projects/ugrid/data/met_base/config/UGridConfig_lfric2
```
```
ERROR  : 
ERROR  : UGridFile::set_dataset() The UGrid dataset "lfric2" is not supported. Please add "/d1/personal/hsoh/git/features/feature_2746_ugrid_nearest_n_points/MET/share/met/config/UGridConfig_lfric2".
ERROR  : 
```
### Test 2
```
POINT_STAT_UGRID_DATASET=
POINT_STAT_MAX_DISTANCE_KM=30
POINT_STAT_UGRID_COORDINATES_FILE=/home/dadriaan/projects/ugrid/data/fcst/lfric/20240112_ftp/lfric_2021-07-28_00.00.00.nc
POINT_STAT_UGRID_CONFIG_FILE=/home/dadriaan/projects/ugrid/data/met_base/config/UGridConfig_lfric2
```
```
ERROR  : 
ERROR  : process_command_line() -> ugrid_dataset is not defined at the configuration file.
ERROR  : 
```

**Comment by JohnHalleyGotway** [comment]
Reassigning this PR to the beta5 development cycle and convert it to draft until work can resume on it.

**Comment by DanielAdriaansen** [comment]
@DanielAdriaansen update contributors guide to say the word `squash` in this section: https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#merge-the-pull-request-and-ensure-that-all-tests-pass.

**Comment by DanielAdriaansen** [comment]
@georgemccabe Could we change:
`POINT_STAT_MAX_DISTANCE_KM` to `POINT_STAT_UGRID_MAX_DIST_KM`
`GRID_STAT_MAX_DISTANCE_KM` to `GRID_STAT_UGRID_MAX_DIST_KM`

If you feel we should spell out `DISTANCE`, I don't have a problem with that just trying to keep them short. But I do think we should include `UGRID` in the conf item name.

**Comment by georgemccabe** [comment]
@DanielAdriaansen, I name the METplus config variables after the name of the corresponding MET config variable and tool so users can infer the names of the METplus config variables. It is easy to support both `POINT_STAT_MAX_DISTANCE_KM` and `POINT_STAT_MAX_DIST_KM`, but the variable name that matches the MET variable would take precedence if both are set.

**Comment by DanielAdriaansen** [comment]
> @DanielAdriaansen, I name the METplus config variables after the name of the corresponding MET config variable and tool so users can infer the names of the METplus config variables. It is easy to support both `POINT_STAT_MAX_DISTANCE_KM` and `POINT_STAT_MAX_DIST_KM`, but the variable name that matches the MET variable would take precedence if both are set.

OK, and big 🤦 on my part, you already have `UGRID` in the conf items, despite me requesting incorrectly above. Thanks for getting it right even though I had it wrong! I think just using `DISTANCE` is good, no need to support `DIST`. Thanks!

**Review by DanielAdriaansen — APPROVED** [review]
I have finished testing these changes with the latest MET changes and approve. Thanks @georgemccabe!

**Pull request merged**
