### PR TITLE
METexpress release guide

### LINKED ISSUE #673: Internal: Create a METplus "Release Guide" describing how to build releases for the METplus components.
## Describe the Task ##
Please see [METplus meeting notes](https://docs.google.com/document/d/1nkAPFijlJq3X3vuOBVBPgVSzTn6IUMEAO_gnEaLskyg/edit#) from 10/27/2020 for more details. This task is to create a 3rd document for METplus in addition to the user and contributor's guides. This document will describe the process for creating a METplus release and consist of up to 8 chapters:
1. Introduction
2. METplus Release
3. MET Release
4. METdatadb Release
5. METcalcpy Release
6. METplotpy Release (or combine METcalcpy/METplotpy into a single chapter if that makes sense?)
7. METviewer Release
8. METexpress Release

The docs/Release_Guide directory will contain .rst files for each of the items listed above. It should also contain a subdirectory named "release_steps". Each top-level .rst file should be very sparse and consist basically of 3 bulleted lists:
- official release (e.g. vX.Y)
- bugfix release (e.g. vX.Y.Z)
- development release (e.g. vX.Y-betaN or vX.Y-rcN)

Each element in that list should source on .rst files that live in the "release_steps" sub-directory. It'd be cool if that content could be hidden by default, but click on it to expand it. So while we have separate lists for each component, they serve up common content from the "release_steps" directory.

Migrate content from:
Existing wiki page:
   https://github.com/dtcenter/METplus/wiki/Creating-a-new-METplus-release
Creating met-10.0_beta1 release:
   https://github.com/dtcenter/MET/issues/1523#issuecomment-714781834

### Time Estimate ###
4-8 hours for many different people.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*
May need to break this down, but not quite sure how to do so yet.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: George (METplus), John HG (MET), Minna (METplotpy/METcalcpy), Tatiana (METviewer), Julie (docs infrastructure), Venita (METdatadb) and Molly (METexpress)
- [x] Select **scientist(s)** or **no scientist** required: Keith (review and advise)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Details for each component will live in the common METplus Release Guide. So all changes will be in the METplus repo.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
- [ ] Documentation builds succeed.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- [ ] n/a

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? Yes

- [ ] Do these changes include sufficient testing updates? No

- [ ] Will this PR result in changes to the test suite? No</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — COMMENTED** [review]
Molly, 

Thank you for putting this METexpress release guide together.  METexpress is quite different from the other components.

Official Release Guide
I noticed that there is no “Open Release Issue” or “Create Release Feature Branch”. These steps are in the other components repositories so that there can be a pull request review of the Release Notes.  You may or may not find that useful for METexpress.

I was unable to test the git clone command due to not being able to find git version 2.23 or higher on a machine. I was also unable to test the opening of an ssh tunnel to mats.gsd.esrl.noaa.gov, along with other steps under “Roll App Versions and Build”.  Would you like to add someone with access to review these items for more thorough testing before this pull request is approved?

Under “Checkout the Development Branch”, I don’t entirely understand what is going on with multiple “git checkout development” and “git pull” commands. In my past experience I’ve only needed to do one of each, so I just wanted to make sure that this is what you want here under “Checkout Development Branch” (steps listed below), and in other sections like “Checkout the Main Branch”, “Merge Development Changes to Main Branch”, “Pull Changes, Create Release Branch, And Merge To Development”

git checkout development
git pull
cd MATScommon
git checkout development
git pull
cd ../METexpress
git checkout development
git pull
cd MATScommon
git checkout development
git pull
cd ../..

I noticed that “Rotate Authorship” is the last item in metexpress_official.rst, but there is no mention of committing any changes made in the rotating of authorship to the repository for the release, so I’m wondering if that step should be pushed up to an earlier step before commits are made (e.g. Before “Pull Changes, Create Release Branch, And Merge To Development”)?

In metexpress_official.rst, there is no “Update the Documentation on the Web”, which has the developer update the version that “latest” points to on ReadtheDocs to point to the newly released version. It would be good to add that as the last step:
.. include:: release_steps/update_docs_official.rst

Development Release Guide

It looks like this section is written to describe developmental work as opposed to a Development Release. Throughout a development cycle, the METplus components have has various beta releases.  For this past cycle, we released beta1 - beta5.   They are releases of newly added features for users to test.  Does METexpress also have these incremental beta releases?  I am not sure exactly what this means “Any code changes will be automatically incorporated into METexpress development container builds once the pull request is approved.”, so maybe that covers a “vX.Y.Z-betaN release”, but I am unsure.

Bugfix Release Guide

I am not sure how METexpress handles bug fixes, but I noticed there was no Bugfix Release Guide for METexpress but there are for the other METplus components.

**Comment by mollybsmith-noaa** [comment]
Hi Julie,

You don't go to the METexpress/METviewer collaboration meetings (please don't feel obligated to do this!), but the METexpress development and release process is quite different from the rest of the METplus components. METexpress uses more of an "agile" development philosophy than the other MET components, doing lots of small official releases, rather than beta or rc releases followed by one giant quarterly official release. If we detect a bug, we just fix it in the next official release. METexpress is also different in structure from the rest of the METplus components, but these steps do accurately convey our release process. To address your comments:

I left out the pull request-related steps for the official release because I'm the one who has the authority to merge code to main, but I'm also the one who does the releases, so I'd end up approving my own pull requests. This seemed redundant, but I can add it it if you think it's necessary.

No one outside of GSL is going to be able to complete these steps, at many require GSL VPN access and permissions (noted in the release guide). It is possible for non-GSL people to build and deploy METexpress containers, as documented in our user's guide, but I was trying to accurately document the steps taken by me (or Randy as my backup) to do an official release. I just followed the draft of these steps when I did the last release, and everything worked, so I'm not sure they need additional testing, and doing another release now will mess up our version numbers. I do expect to tweak these instructions for clarity as I use them with future releases, but I think they work well enough for a first draft.

Unlike the other METplus components, MATS/METexpress makes use of sub-repos, which is why you see the repeated checkout and pull statements--you have to do that for each repo involved. The git 2.23 requirement for cloning was an attempt by me to make the syntax simpler (one line to clone all of the sub-repos, instead of about ten lines), but I can swap this out if you think it will be overly onerous.

That's a good point about the rotate authorship section. I added that when you requested it after I had done the release, so that's the one section that wasn't tested. I'll move that up in the workflow. I can add the documentation update section as well.

Our development releases are not really official releases, as the development code is built nightly, but it is technically a "release" that gets installed on our servers, so I thought I would include the (much simpler) steps here. As I mentioned before, we don't really do bugfix releases.

Let me know if any of this needs clarification?

Thanks!
Molly

**Review by jprestop — APPROVED** [review]
Thanks for taking the time to explain everything. 

> I left out the pull request-related steps for the official release because I'm the one who has the authority to merge code to main, but I'm also the one who does the releases, so I'd end up approving my own pull requests. This seemed redundant, but I can add it it if you think it's necessary.

I think you should do whatever works best for METexpress.  If it seems redundant, it is ok to leave out, I just wanted to explain why it was in the other components' guides in case it wasn’t clear and in case you would find it useful.

Thank you for following the draft of these steps when you did the last release.  I’m glad everything worked well.  It sounds like they don’t need any additional testing. As you indicated and as with the other components’ guides, tweaking is expected.

Thank you for explaining the repeated checkout and pull statements are due to sub-repos. I have no experience with those, but now I know something more than I did before, so that’s great.  

I think the 2.23 requirement is perfectly acceptable, especially since you and Randy have access to it and will be the ones doing the work.  I also appreciate simpler syntax and don’t think you should swap it out.  I just wasn’t familiar with it.   I appreciate being exposed to these things here so that I can become more familiar with it.

Thank you also for explaining about your development and bugfix releases.  

Once you move up the authorship section and add in the documentation update section, I think this is good to go.  

I approve this request. Please let me know if you are not able to merge it into the repository and I will take care of that step for you. 

Have a great weekend!

**Comment by mollybsmith-noaa** [comment]
Hi Julie,

I’m out on leave today, but I’ll take care of this first thing tomorrow! Do you want me to make the changes we discussed before merging, or merge, make the changes, and then submit another pull request? Probably the latter?

Thanks!
Molly

**Comment by jprestop** [comment]
I think making the changes before the merge would be fine.  I'm happy to review the changes again before you merge if you'd like. They are also minor changes, so if you don't feel like it needs review, please feel free to go ahead and "Squash and merge".  Enjoy your day off!

**Comment by mollybsmith-noaa** [comment]
I made the requested addition and reorder in metexpress_official.rst, and all tests pass, so I'm merging this pull request.

**Pull request merged**
