### PR TITLE
feature 711 skip if output exists

### LINKED ISSUE #711: Support SKIP_IF_FILE_EXISTS for all wrappers
Most wrappers support this functionality (i.e. PCP_COMBINE_SKIP_IF_OUTPUT_EXISTS) but it would be nice to support it in all wrappers so there is no question if the capability is available when someone asks (someone asked).

## Describe the Enhancement ##
Check that all wrappers handle the configuration appropriately and add support if they do not.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>
Ran each wrapper and verified that it skips processing if {APP_NAME}_SKIP_IF_OUTPUT_EXISTS is True and output exists

- [X] Recommend testing for the reviewer to perform, including the location of input datasets:
* Try running a few use cases twice with config.{APP_NAME}_SKIP_IF_OUTPUT_EXISTS=True i.e. config.GRID_STAT_SKIP_IF_OUTPUT_EXISTS=True
* Review output on kiowa to ensure everything is run as expected
Data created by the develop branch is in /d1/personal/mccabe/test-use-case-b-dev
Data created by the feature branch is in /d1/personal/mccabe/test-use-case-b
Note: Filenames for MTD output will change due to the changes to align the valid time referenced in the MET output to the directories and intermediate file list files

- [X] Will this PR result in changes to the test suite? **[Sort of]**</br>
A bug was discovered in the output file naming of MTD output. Filenames will change (for the better)
All tests should still pass (and they do)

- [X] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Comment by jprestop** [comment]
`Try running a few use cases twice with config.{APP_NAME}_SKIP_IF_OUTPUT_EXISTS=True i.e. config.GRID_STAT_SKIP_IF_OUTPUT_EXISTS=True`
Are particular use cases that would be better to test than others or does it not matter at all?

`Review output on kiowa to ensure everything is run as expected
Data created by the develop branch is in /d1/personal/mccabe/test-use-case-b-dev
Data created by the feature branch is in /d1/personal/mccabe/test-use-case-b
Note: Filenames for MTD output will change due to the changes to align the valid time referenced in the MET output to the directories and intermediate file list files`
I'm trying to find the output dirs to check some output...  Ah, nevermind!  I see what's going on now.  I was confused by the directories being named with a ".conf" extension.  Is that naming just for the testing environment?

**Comment by georgemccabe** [comment]
@jprestop I ran a use case from each directory under met_tool_wrapper. You could run a few from model_applications and set the skip config variable for each item in the PROCESS_LIST to see if they are all skipped properly.

The output is separated into the directories that end with .conf to keep all use cases runs separate so they don't mistakenly succeed because other data is available. Travis CI uses a more updated test suite that doesn't include the .conf extension, but uses the same names. I still need to update the use case test script to run that way. The new was reads all of the use cases from internal_tests/use_cases/all_use_cases.txt instead of using the dictionary inside the script.

**Comment by jprestop** [comment]
Thanks, George.  I've compared some output and it is all as expected.  I am confused about something though.  I expected to see "SKIP_IF_OUTPUT_EXISTS" somewhere in the metplus_final.conf files, but am not seeing that.  What am I not understanding?
`kiowa::/d1/personal/mccabe/test-use-case-b-dev> grep SKIP_IF_OUTPUT_EXISTS metplus_final.conf
kiowa::/d1/personal/mccabe/test-use-case-b-dev> 
`
`kiowa::/d1/personal/mccabe/test-use-case-b> grep SKIP_IF_OUTPUT_EXISTS metplus_final.conf
kiowa::/d1/personal/mccabe/test-use-case-b>`

**Comment by georgemccabe** [comment]
The metplus_final.conf files you are looking at are for the setup of the use case script. There are metplus_final.conf files in each of the subdirectories for each run. Not all of those runs will necessarily have the *_SKIP_IF_OUTPUT_EXISTS because not all use cases set that variable explicitly. Comparing this output is just to ensure nothing broke from the changes. Running cases by hand twice and setting the variables, i.e. config.GRID_STAT_SKIP_IF_OUTPUT_EXISTS=True (added to command line call) is the test to ensure that it actually skips if requested.

**Comment by jprestop** [comment]
>  Running cases by hand twice and setting the variables, i.e. config.GRID_STAT_SKIP_IF_OUTPUT_EXISTS=True (added to command line call) is the test to ensure that it actually skips if requested.

Thanks for being explicit here with the "(added to the command line call)".  I was expecting to see it in your process list but now I understand why it is not.

**Review by jprestop — APPROVED** [review]
I ran the Grid-Stat: Compute Anomaly Correlation using Climatology test case to ensure that case ran as expected with SKIP_IF_OUTPUT_EXISTS, reviewed output on kiowa to ensure everything ran as expected, and reviewed the files changed. Everything looks good to me.  Lots of work here!  Thank you for all of your work on this task!

**Comment by jprestop** [comment]
I forgot to add that I didn't merge it yet because the test are still running, so I figured we should wait for those to finish before merging.

**Comment by georgemccabe** [comment]
@jprestop the builds haven't finished because we ran out of credits. All of the tests except for 1 ran in the branch build and they had previously succeeded in the pull request build. I think it is safe to merge the changes, so I will do that now. Thanks for reviewing this!

**Comment by georgemccabe** [comment]
@jprestop I forgot to mention that to make testing easier and since the refactor it is now possible, I added an ExtractTiles met_tool_wrapper example to the repo. I did forget to add it to the test cases list, so I will do that now.

**Comment by jprestop** [comment]
Thanks, George.  Also, I forgot to ask - did you update the documentation for this option and for the ExtractTiles example?

**Comment by georgemccabe** [comment]
@jprestop I did create a use case document for the new ExtractTiles example. I rendered it locally just now and noticed that there is somehow some warnings that I missed. Many of the wrappers already had glossary entries for their _SKIP_IF_OUTPUT_EXISTS config, but I realize now that I didn't add them for the new ones. I will re-open the issue take care of those things.

**Pull request merged**
