### PR TITLE
Added function to format [fcst/obs]_level - Issue #407

### PR DESCRIPTION
**Pull request by georgemccabe**
the way StatAnalysis expects it, added tests

### CODE REVIEW

**Comment by georgemccabe** [comment]
There is a config file on kiowa that you can test running METplus.

/home/mccabe/StatAnalysis_netcdf.conf

It sets the level list values with and without parenthesis, and you can see the result works for both.

FCST_LEVEL_LIST = "0,*,*"
OBS_LEVEL_LIST = "(20170510_060000,*,*)"

**Comment by JohnHalleyGotway** [comment]
I tested this change on kiowa in /d1/projects/METplus/METplus_pull_requests/pull_request_425.  I ran using the /home/mccabe/StatAnalysis_netcdf.conf config file that the developer provided.  I confirmed that the StatAnalysis wrapper strips off parenthesis from the FCST_LEVEL_LIST and OBS_LEVEL_LIST settings and made sure it still works for list lengths > 1:
   FCST_LEVEL_LIST = "(0,*,*)","(0,*,*)"

**Review by JohnHalleyGotway — APPROVED** [review]
Please be sure to also make these same changes in the develop branch for inclusion in the next release.

**Comment by georgemccabe** [comment]
Merging changes into master_v3.0 as a bugfix.

**Comment by georgemccabe** [comment]
this didn't get merged!

**Comment by georgemccabe** [comment]
Now closing.

**Pull request merged**
