### PR TITLE
feature 1069 TCPairs write_valid, valid_inc, valid_exc

### LINKED ISSUE #1069: Enhance TC-Pairs wrapper to make valid_inc, valid_exc, and write_valid configurable options.
## Describe the Enhancement ##
dtcenter/MET#1870 adds 3 new configurable options for TC-Pairs. This task is to enhance the METplus TC-Pairs wrapper to make those options configurable:
```
valid_inc   = [];
valid_exc   = [];
write_valid = [];
```
All 3 are arrays of strings that are empty be default. The can be filled with a comma-separated list of double-quoted string in "YYYYMMDD[_HH[MMSS]]" format. They configuration of them is exactly the same as the existing init_inc and init_exc options.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541 (copied from dtcenter/MET#1870)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: George
- [x] Select **scientist(s)** or **no scientist** required: Molly Smith

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
Assigned to the beta2 cycle, but this can be moved to beta3 if needed.
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
Added support for new MET config variables

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Added unit tests to ensure that correct value for environment variable is set

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review code changes, optionally test setting values in the METplus config file and verify that the values are set properly in the MET config. You will need a version of MET that supports these new configs to test.

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **8/31/2021** to be included in beta2, end of the week if not.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by mollybsmith-noaa** [comment]
@georgemccabe Is this code somewhere on Jet for testing?

**Comment by georgemccabe** [comment]
> 
> 
> @georgemccabe Is this code somewhere on Jet for testing?

@mollybsmith-noaa, it is not but I can put it there if that would be helpful. Let me know if you'd like me to do that.

**Comment by mollybsmith-noaa** [comment]
> > @georgemccabe Is this code somewhere on Jet for testing?
> 
> @mollybsmith-noaa, it is not but I can put it there if that would be helpful. Let me know if you'd like me to do that.

If you don't mind, that's where I have all of my MET-TC with rocoto set up.

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

There are 7 modified files which make the TC-Pairs valid_inc, valid_exc, and write_valid options configurable via METplus:
- 2 .rst documentation files
- 1 test script
- 1 tc_pairs python wrapper
- 1 wrapped tc_pairs config file
- 2 METplus conf files for tc_pairs

These changes look fine to me.

**Pull request merged**
