### PR TITLE
Feature #1626 TCDiag Wrapper

### LINKED ISSUE #1626: New Wrapper: TC-Diag
## Describe the New Feature ##
dtcenter/MET#2168 defines a new tool named TC-Diag (for Tropical Cyclone Diagnostics). It's inputs are almost identical to the existing TC-RMW tool. However, it will have different functionality. This task it to create a wrapper for the new TC-Diag tool, supporting all available configuration options.

Note that this work depends on the TC-Diag tool being created.

Once this wrapper is created, recommend creating a use case to demonstrate it. The issue for that use case HAS NOT YET been defined.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*NOAA WPO - JTTI TCDiag Project (2770043)*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: @jvigh and @KathrynNewman 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] dtcenter/MET#2168

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by georgemccabe**
Note that the wrapper is in "beta" and has not been properly tested with the actual MET tool being developing in dtcenter/MET#2168

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Added unit tests to confirm correct values are set in environment variables read by wrapped MET config file and commands are built correctly.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review code changes for any typos or potential issues

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[No]**

We will perform more testing after the MET tool is made available and fix any bugs before the official release.

- [X] Will this PR result in changes to the test suite? **[No]**</br>

New use case is not yet run in the automated tests

- [X] Please complete this pull request review by **6/6/2023**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Review the source issue metadata (required labels, projects, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by georgemccabe** [comment]
Merging this PR without review to get it into rc1 release since further testing will be done when the MET tool is completed.

**Comment by jvigh** [comment]
@mccabe and @KathrynNewman , I reviewed this basic use case for the TC-Diag tool
 and made some enhancements.

For reference, the resulting documentation can be viewed at: https://metplus.readthedocs.io/en/develop/generated/met_tool_wrapper/TCDiag/TCDiag.html#sphx-glr-generated-met-tool-wrapper-tcdiag-tcdiag-py

The METplus use case references the MET documentation: https://met.readthedocs.io/en/feature_2558_tc_diag_docs/Users_Guide/tc-diag.html

I noted that users can obtain real-time GFS-FV3 data at: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20230626/

I modified the description section of the [documentation page for the METplus Python Wrappers tool](https://metplus.readthedocs.io/en/feature_1626_tc_diag_v2/Users_Guide/wrappers.html#tcdiag) to include a little bit more about the intended purpose of the tool. 

I modified the [use case page for the basic TC-DIAG wrapper](https://metplus.readthedocs.io/en/feature_1626_tc_diag_v2/generated/met_tool_wrapper/TCDiag/TCDiag.html#sphx-glr-generated-met-tool-wrapper-tcdiag-tcdiag-py) to add an overview, scientific description, and additional data details. 

**Question #1:** This use case appears to use retrospective forecast data from Hurricane Matthew (2016). The times included are rather odd and would not represent typical usage of the tool (which would normally be run with lead times at 6-h intervals out to 126 h or 168 h). **Should the sample data be updated to provide fields for the more typical times that users would normally run (e.g., 0, 6, and 12 h)?** 

**Question #2:** I looked for additional key words and found TCandExtraTCAppUseCase. That seemed to fit so I added it. I also noticed FeatureRelativeUseCase. **Since the diagnostics are computed following the moving storm center, should this keyword be added? Or is that keyword intended in a different manner?**

I am not quite done with my review. I still need to run the use case and see if there are some additional enhancements that can be noted in the example that makes it more scientifically interesting. I'll try to do this tomorrow.

**Comment by jvigh** [comment]
@georgemccabe, @KathrynNewman, and @jprestop  Do you know the location of the MET v11.1.0-rc2 build on Seneca?

I'd like to test this use case, but am not sure where the rc2 build of MET is installed. For future reference, where would I find out this type of information? I checked the builds page on the DTC website, and the info was not filled in. Does this mean the RC2 build isn't yet available on Seneca?

image

**Comment by georgemccabe** [comment]
Hi @jvigh,

Let's discuss your questions in the TCDiag meeting this afternoon.

MET v11.1.0-rc1 (there is no rc2 at the moment) is not currently installed on seneca. I can install it on there now.

To avoid confusion, it would be good to continue this discussion on the open issue #1626 instead of this merged PR. I will comment on there when the rc1 release is installed on seneca.

**Pull request merged**
