### PR TITLE
feature 1067 main_v4.0 install instruct

### LINKED ISSUE #1067: Fix installation instructions in User's Guide
## Describe the Problem ##

The current installation instructions tell users to use the scripts in the build_components directory to install MET and other METplus components:

https://metplus.readthedocs.io/en/v4.0.0/Users_Guide/installation.html#build-components-and-using-manage-externals

However, the script does not work and produces many errors. There will be a separate issue to fix the scripts, but in the meantime we should update the documentation to direct users to download the latest release tarfile and refer to the installation instructions in chapter 2 of the MET User's Guide instead of using these scripts.

These changes should be applied to the main_v4.0 and develop branches.

A recent GitHub Discussions question brought this to attention: https://github.com/dtcenter/METplus/discussions/1059

The comments of this discussion include info provided to the user to get MET installed that can be used as a reference to update the documentation.

### Relevant Deadlines ###
ASAP

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Organization** level **Project** for support of the current coordinated release
- [X] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Worked with George to update the installation instructions.  Looked at the following pages to ensure proper formatting:
https://metplus.readthedocs.io/en/feature_1067_main_v4.0_install_instruct/Users_Guide/installation.html
https://metplus.readthedocs.io/en/feature_1067_main_v4.0_install_instruct/Users_Guide/systemconfiguration.html

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review files changed.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>

- [x] Please complete this pull request review by **[09/17/21]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
It looks like all of the bullet lists no longer have dots anymore. Perhaps it is caused by the extra dash (-) characters in the list items. You could try escaping that character?

**Comment by jprestop** [comment]
@georgemccabe 

> It looks like all of the bullet lists no longer have dots anymore.
I am so glad you looked at the pages.  I reviewed them and didn't even notice that.  Thank you so much.  I'll take a look now.

**Comment by jprestop** [comment]
@georgemccabe 
Yes, something is very wrong.  Even the asterisks for the lists on the release-notes are broken and I didn't even touch that page:
https://metplus.readthedocs.io/en/feature_1067_main_v4.0_install_instruct/Users_Guide/release-notes.html

**Review by georgemccabe — APPROVED** [review]
I reviewed the changes and they all look good. They involve updating the documentation to clearly direct users to the MET installation section of the User's Guide to install MET, removed the section describing the build_MET.sh script because it currently does not work, and some various formatting cleanup.

We discovered that unrelated to these changes, a new version of sphinx and sphinx-rtd-theme caused the bullets in the bulleted lists to disappear. We discovered that two python package versions changed (charset-normalizer-2.0.5 and docutils-0.17.1) and one of them didn't play nicely with the version of sphinx we have been using. We decided to remove the requirements for building the docs in ReadTheDocs to use the version of sphinx and sphinx-rtd-theme that RTD automatically installs. We previously were downgrading the versions of some sphinx packages that risk package conflicts. Using the latest version of sphinx and the sphinx RTD package will reduce the risk of issues and automatically incorporate improvements/bugfixes. Julie and I reviewed the docs and determined that any differences in formatting were improvements.

I approve of this PR.

**Pull request merged**
