### PR TITLE
Feature 1617 v4.1.2

### LINKED ISSUE #1617: Create the METplus v4.1.2 bugfix release
## Describe the Task ##
This task is to create the METplus 4.1.2 bugfix release.

During this process, remember to review and refine the instructions for METplus in the METplus Release Guide:
https://metplus.readthedocs.io/en/develop/Release_Guide/metplus.html

### Time Estimate ###
1-4 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Mid-May

### Funding Source ###
2771021

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Nothing.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review the files changed.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[I don't think so, but perhaps the version number will change something?]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[05/16/22]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@georgemccabe @JohnHalleyGotway 
If you approve of the change to the Release Guide notes, I'd like to make the same change directly in develop.  Thoughts?

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes. I reviewed the release notes [here](https://metplus.readthedocs.io/en/feature_1617_v4.1.2/Users_Guide/overview.html#metplus-version-4-1-2-release-notes-2022-05-16), and the single one looks fine. I checked the METplus repo to confirm that this is the only PR that 4.1.2 actually includes.

**Review by georgemccabe — APPROVED** [review]
The changes look good. I am not sure if it is appropriate to put a link to an internal GitHub issue that users cannot access in the release notes. It will appear to be a broken link for users since they don't have access to the repository. We could either remove the link but still include the issue number, or we could provide a link to the pull request for the changes. Thoughts?

**Comment by jprestop** [comment]
Thanks @georgemccabe.

> I am not sure if it is appropriate to put a link to an internal GitHub issue that users cannot access in the release notes. It will appear to be a broken link for users since they don't have access to the repository. We could either remove the link but still include the issue number, or we could provide a link to the pull request for the changes. Thoughts?

We handled it this way in the MET release notes for 10.1.2.  We added the "METplus-Internal" reference to indicate that it is in a different repo, thinking that the "Internal" reference indicates that it may not be available to all.  I'm ok with proceeding as-is.  @JohnHalleyGotway any additional comments?

**Comment by JohnHalleyGotway** [comment]
We could revise how we handle this. Perhaps keeping the backlog of sensitive issues in METplus-Internal makes sense, but once the issue has been addressed, perhaps we don't need to keep it "hidden" anymore?

We could consider transferring the issue from METplus-Internal to the actual repo either when we begin work on it, when we submit a PR for it, or prior to creating a release?

Or I suppose we could just link to the PR instead of the issue in the release notes.

**Pull request merged**
