### PR TITLE
enhancement 434 ASCII2NC_SKIP_IF_OUTPUT_EXISTS

### PR DESCRIPTION
**Pull request by jprestop**
This is a pull request for issue: https://github.com/NCAR/METplus/issues/434
I have never submitted a pull request before, so hopefully, I have done this correctly.  Please let me know if you have any questions.  Thanks!

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
These changes look great. My only suggestion is please add the new default value to the other ASCII2NC use cases in the met_tool_wrapper area:

ASCII2NC_python_embedding.conf
ASCII2NC_python_embedding_user_py.conf

It would probably be good to check if ASCII2NC is used by any model_applications use cases and add it there if it is, but I don't think there are any (as of now).

You can make these changes directly to your branch and it will automatically add the changes to the pull request when you push them to GitHub.

**Comment by JohnHalleyGotway** [comment]
Julie, please just remove me as a reviewer and use George's feedback.  I'm
going to focus on this bugfix for ascii2nc.

Thanks,
John

**Comment by jprestop** [comment]
Hi George.  I made the requested changes.  It appears that only the following files use ascii2nc:
ASCII2NC_python_embedding.conf
ASCII2NC_python_embedding_user_py.conf

I don't see the new changes in this pull request though, although I did push them to the branch.  How do I proceed so that you can see the changes?

**Comment by georgemccabe** [comment]
@jprestop, your commit now is viewable in the pull request. I think GitHub has been having some issues because I been having problems navigating the website and pushing changes over the last hour. I received an email saying you added a commit 1 minute after your email not being able to see it, so I suspect the issues with the site are to blame.

**Review by georgemccabe — APPROVED** [review]
Thanks, Julie!

**Pull request merged**
